- .gitignore
- README.md
- project-description.md
- pyserini/pyclass.py
- pyserini/search/pysearch.py
This is the package currently deployed at TestPyPI: https://test.pypi.org/project/pyserini/0.6.1.post0/
The fatjar is based on `0ed488` in Anserini, dated `Sun Nov 17 19:08:26 2019 -0500`.
Working colab notebook at: https://colab.research.google.com/drive/1nY1bjwop3Enygrks-208EilhiCYmYKT6
Still need to update docs, but code itself is ready for CR I think.
I'd also appreciate opinions on publishing SNAPSHOT versions of the fatjar that aren't in Maven... Current package is on TestPyPI, so it really doesn't matter... but any strong opinions on publishing in official PyPI?
The tradeoff is between iteration speed vs. "doing it right". PyPI packages are supposed to be permanent, so depending on a snapshot jar is janky.
> Refactoring/Upgrade: Exposing topics and other fixes

- setup.py
Released package per @zeynepakkalyoncu 's request:
https://test.pypi.org/project/pyserini/0.6.1.post1/
SNAPSHOT Anserini fatjar built at:
```
commit c4f3514a297b8e74301d0e90b55fd6b3996588cc
Author: w329li <w329li@uwaterloo.ca>
Date:   Sun Dec 1 06:40:54 2019 -0500
```
> TestPyPI 0.6.1.post1

- tests/test_collection.py
> Test case for iterating through the CACM collection

- pyserini/index/pyutils.py
- tests/test_indexutils.py
Add functionality to fetch raw document given its collection docid
Python wrapper over getRawDocument: https://github.com/castorini/anserini/pull/937
> Fetch raw document

- README.md
- release-notes/release-notes-v0.7.2.0.md
Updated README to feature new functionality.
> Release notes for v0.7.2.0

- README.md
- project-description.md
- pyserini/index/pyutils.py
- tests/test_indexutils.py
+ IndexTerm (and Posting from previous patch)brought up to top level (not inner classes)
+ Removed dump_document_vectors
+ Better tests
+ Added type hints
+ Cleaned up docstrings
> Refactoring of pyutils

- README.md
- pyserini/collection/pycollection.py
- pyserini/index/pygenerator.py
- pyserini/pyclass.py
- pyserini/search/pysearch.py
- pyserini/setup.py
- tests/test_collection.py
- tests/test_loadtopics.py
- tests/test_search.py
+ Brought all code up to PEP 8 standard
+ Refactoring of pysearch:
- Created Document object to wrap raw Lucene documents
- Updated some docstrings
- Added some type hints
- Added more test cases
+ Document class in pycollection renamed SourceDocument to match Anserini class name
> Lots of refactoring

- README.md
- pyserini/index/pyutils.py
- pyserini/pyclass.py
- tests/test_analysis.py
- tests/test_indexutils.py
Closes #47 but also requires https://github.com/castorini/anserini/pull/1023
cc/ @Oulaolay
> Added ability to fetch postings based on analyzed form

- pyserini/search/pysearch.py
Previously, there was no proper method exposed in Anserini to dispatch to. That's been fixed, so we're now fixing the connection on the Pyserini end with this PR.
> Fixed TODO in pysearch, dispatching to appropriate method in anserini

- README.md
- pyserini/collection/pycollection.py
- pyserini/index/pygenerator.py
- pyserini/index/pyutils.py
- pyserini/pyclass.py
- pyserini/search/pysearch.py
- tests/test_collection.py
- tests/test_indexutils.py
Propagates recent changes to anserini.
cc @hscells
> Refactoring to bring pyserini back into alignment with anserini HEAD

- pyserini/pyclass.py
- pyserini/search/pysearch.py
- tests/test_search.py
the `SimpleNNSearcher` class exposes Anserini's `SimpleNearestNeighborSearcher` features in pyserini.
> added SimpleNNSearcher class

- bin/generate_trec_covid_round1_OSHU_RUN2.py
Script written by Jimmy Chen, School of Medicine, OHSU
Checked into Pyserini with minimal modification from script sent to me over email. Will refactor after initial commit into code base.
> Replication script for OHSU_RUN2 for TREC COVID round 1

- pyserini/search/pysearch.py
- tests/test_loadtopics.py
Provides convenient access without needing to bother with parsing topic files.
> Exposes TREC-COVID topics

- README.md
Better interleaving of explanations for code.
@PepijnBoers take a look also?
> Improved documentation for IndexReaderUtils

- README.md
- pyserini/index/pyutils.py
- tests/test_indexutils.py
Makes methods in IndexReadUtils more consistent (resolves https://github.com/castorini/pyserini/issues/93) + update README.md
> Make methods in IndexReaderUtils more consistent

- pyserini/pyclass.py
- pyserini/search/pysearch.py
Questions: 
1. how to initialize a indexSearcher in pysearcher? 
I have checked available constructors either need a reader or readerContext. How can I access those two?
2. Is there any documents I can follow to run the whole pysenrini locally and test the changes?
> add a field to pysearcher made it expose to 'n' (number of docs in the index)

- README.md
Create an example on how to construct queries in Pyserini
> Create documentation for Query building

- pyserini/search/pysearch.py
Pyserini end of this Anserini PR: https://github.com/castorini/anserini/pull/1189
> SimpleSearcher refactoring

- .gitignore
- README.md
- collections/.gitkeep
- indexes/.gitkeep
+ Instead of throwing everything in the directory at top level, reorganized into sub-directories.
+ Updated query builder docs
> Repo reorg, updated documentation

- pyserini/index/pyutils.py
- tests/test_indexutils.py
Python counterpart PR of https://github.com/castorini/anserini/pull/1196
> Allow setting of BM25 parameters

- scripts/verify_simplesearcher.py
- per title
----------------------------------
> Add evaluation results to verify_simplesearcher.py

- pyserini/search/__main__.py
- pyserini/search/reranker.py
- pyserini/vectorizer.py
- requirements.txt
- scripts/ensemble_average.py
Sample Command
----------------
```
python -m pyserini.search \
-index /Users/johnson/anserini/indexes/lucene-index.robust04.pos+docvectors+raw \
-topics robust04 \
-output robust04-prf.txt \
-prf -alpha 1
```
bm25 + LR on robust04 (alpha=1)
----------------
```
map                   	all	0.2550
P_30                  	all	0.3138
```
> Pseudo Relevance Feedback Interpolation on pysearch

- scripts/classifier_prf/cross_validate.py
- Refactor the code a little here
- while fixing a bug that hardcoded the qrel path to `core18`.
> cross_validate.py should work collections other than core18

- scripts/classifier_prf/cross_validate.py
- Adding boilerplate to cross_validate.py
> Add boilerpate to cross_validate.py

- pyserini/vectorizer.py
- tests/test_indexutils.py
- Add boilerplate at top of `vectorizer.py`
- Add test case for tfidf vectorizer
- Add doc_str for tfidf_vectorizer's class and public method
> Test case for tf-idf vectorizer & include licensing info

- .gitignore
- .gitmodules
- README.md
- docs/release-notes/release-notes-v0.9.3.0.md
- tests/test_loadtopics.py
+ Added https://github.com/castorini/anserini-eval as submodule, per https://github.com/castorini/anserini/issues/1216
+ Cleaned up gitignore, fixed typo in test cases.
@ronakice @rodrigonogueira4 @edwinzhng can you check if I did it correctly?
> Added eval submodule, general cleanup

- pyserini/search/pysearch.py
- tests/test_loadtopics.py
Pyserini end of https://github.com/castorini/anserini/pull/1245
> Add TREC News bindings

- tests/test_indexutils.py
- Add a new test case for BM25Vectorizer on Linear Regression model.
> Testcase for BM25Vectorizer on Linear Regression model

- .gitmodules
- README.md
Uses `https` for cloning. Makes consistent with anserini and pygaggle.
> Tweaks to eval/ submodule

- pyserini/vectorizer.py
- Adopting sklearn's L2 norm function which is designed for [csr_matrix](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/preprocessing/_data.py)
> Adopt sklearn's L2 norm function

- pyserini/search/__main__.py
- pyserini/search/reranker.py
- add the option of using BM25Vectorizer to pyserini.search
> Introduce BM25Vectorizer to pyserini.search

- docs/source/conf.py
- docs/source/index.rst
- docs/source/pyserini.analysis.rst
- docs/source/pyserini.collection.rst
- docs/source/pyserini.index.rst
- docs/source/pyserini.search.rst
- pyserini/analysis/__init__.py
- pyserini/analysis/_base.py
- pyserini/collection/_base.py
- pyserini/index/_base.py
- pyserini/search/_searcher.py
- tests/test_analysis.py
- tests/test_search.py
Corrected minor issues with code, added tests along the way.
> Cleanup of docstrings, refactored sphinx RST docs

- README.md
- docs/usage-analyzer.md
- docs/usage-collection.md
- docs/usage-indexreader.md
- docs/usage-pyjnius.md
- docs/usage-querybuilder.md
Closes #119 - also adopts @rodrigonogueira4 's suggestion of what to focus documentation on.
> Refactoring docs to break into subpages

- pyserini/fusion/__main__.py
- pyserini/fusion/_base.py
- pyserini/trectools/_base.py
- Add merge aggregation and rescore logic to `TrecRun` class
- fusion/__main__.py has two new parameters
- `depth` => pool depth from each topic
- `k` => number of docs to output per topic after fusion
> TrecRun should contain aggregation and rescore logic

- pyserini/fusion/_base.py
- pyserini/search/__init__.py
- pyserini/search/__main__.py
- pyserini/search/_searcher.py
- pyserini/trectools/__init__.py
- pyserini/trectools/_base.py
- We need a test case with more than one Lucene index. @lintool any suggestions?
- Doc str after the implementation is finalized.
```
from pyserini.search import SimpleFusionSearcher
from pyserini.trectools import FusionMethod
index_dirs = [
'../anserini/indexes/lucene-index.core17.pos+docvectors+raw',
'../anserini/indexes/lucene-index.core18.pos+docvectors+raw',
'../anserini/indexes/lucene-index.robust04.pos+docvectors+raw',
'../anserini/indexes/lucene-index.robust05.pos+docvectors+raw'
]
searcher = SimpleFusionSearcher(index_dirs, method=FusionMethod.RRF)
hits = searcher.search('hubble space telescope')
for i in range(0, 10):
print(f'{i+1:2} {hits[i].docid:15} {hits[i].score:.5f}')
```
> Fusion searcher

- pyserini/fusion/__init__.py
- pyserini/fusion/__main__.py
- pyserini/fusion/_base.py
- tests/resources/simple_trec_run_average_verify.txt
- tests/test_fusion.py
- introduce new fusion method by averaging
- include test case
> Introduce new fusion method by average

- scripts/verify_simplesearcher.py
- linting to code to use a max length of 120 chars
- better license boilerplate
> verify_simplesearcher.py code lint and proper license

- README.md
- docs/release-notes/release-notes-v0.9.3.1.md
@x65han lmk if I've forgotten anything?
> Release notes for v0.9.3.1

- integrations/simplesearcher_check_robust04.py
- integrations/simplesearcher_checker.py
What do you think? The idea is that each collection would be its own test case.
If you like, I'll add in the other collections.
> Refactor verify_simplesearcher as integration tests

- .gitignore
- README.md
- docs/experiments-msmarco-passage.md
I think this is going to make a lot of people happy!
> Add MS MARCO passage retrieval replication in pure Python

- README.md
- integrations/resources/sample_collection_json/doc1.json
- integrations/resources/sample_collection_json/doc2.json
- integrations/resources/sample_collection_json/doc3.json
- integrations/resources/sample_collection_json_array/documents.json
- integrations/resources/sample_collection_jsonl/documents.jsonl
This is just a start... but should make lots of people happy!
> Add documentation on how to index your own documents

- docs/working-with-spacy.md
Issue #168
@lintool Because at most of the cases, we want to run NLP on document's `contents` instead of `raw`, it would be great to have a pre-built index storing `contents`. I have built one on core18, maybe it's worth to upload it [here](https://git.uwaterloo.ca/jimmylin/anserini-indexes)?
> Add a guide about working with Pyserini and spaCy

- pyserini/fusion/__main__.py
- pyserini.fusion should use RRF by default
> pyserini.fusion should use RRF by default

- integrations/simplesearcher_checker.py
+ Improved error status checking
+ Fixed broken path
> Light refactoring of integration tests

- integrations/test_simple_fusion_search_integration.py
- pyserini/util.py
Rewrote fusion test case using this submodule - this is cleaner and more portable then calling out to shell.
> Add util submodule for downloading indexes and other files

- docs/working-with-cord19.md
- scripts/cord19/extract_citation_graph.py
Update import queries to combine citation graph with BLENDER knowledge graph.
* Update script to add pmcid property.
* Update Cypher queries for compatible node labels.
> Add compatibility with BLENDER knowledge graph

- docs/working-with-spacy.md
Add indexing command for core18 with option "-storeContents"
> Improve doc "working with spacy"

- pyserini/collection/_base.py
- pyserini/index/_base.py
* Added AclAnthology to JCollections; added AclAnthologyGenerator to JGenerators
* Verified manually in iPython with https://github.com/castorini/pyserini/blob/master/docs/usage-collection.md
> [#231] Added AclAnthology and AclAnthologyGenerator

- README.md
> Update README for indexing additional fields

- pyserini/util.py
Definition `local_tarball` needs to be pulled out of the if branch to top level, otherwise when the else branch is taken, the variable won't be defined when used later.
> Index download bugfix

- pyserini/search/__main__.py
- pyserini/search/_searcher.py
try to use pre-built indexes from command-line
An example:
```
python -m pyserini.search --topics msmarco_doc_dev \
--index ms-marco-doc \
--output runs/run.msmarco-doc.dev.bm25.txt --bm25
```
> Using pre-built indexes from command-line

- integrations/test_simple_fusion_search_integration.py
Reorganized by Dropbox files. Fixed link.
> Fixed Dropbox link

- pyserini/util.py
- scripts/check_download_links.py
Tweaked regexp to match MD5 checksums more exactly.
In case of MD5 mismatch, display expected and actual.
> Minor improvements to check_download_links script

- README.md
- docs/20newgroups.md
- docs/working-with-cord19.md
@lintool  Today, I tried everything again and it all works. I am not really sure why I got ramdom 0.077 yesterday, maybe my computer cache? 
If you think this instruction is good, maybe can you ask someone else also try it to see if they can stably get around 0.83 score?
And when I work with cord19 using pyserini, I found you refactoring the pyserini collection but the readme is not updated.
> replace 20newsgroups text classification demo

- pyserini/index/_base.py
- pyserini/prebuilt_index_info.py
- pyserini/search/_searcher.py
- pyserini/util.py
+ Robust04 index moved, fixed location
+ Added ability to download from alternate URLs
+ Added method to validate index stats
+ Fixed check to see if index has been downloaded
> Improved downloading of prebuilt indexes

- pyserini/search/__main__.py
+ implemented maxP to be able to search MS MARCO doc per-passage conditions
+ automatically sets BM25 parameters
> Improvements to pyserini search CLI

- pyserini/prebuilt_index_info.py
Add trec-covid round1-5  pre-built index
> add trec-covid pre-built index to pyserini

- pyserini/prebuilt_index_info.py
> Added TREC CaST 2019 prebuilt index

- README.md
- docs/prebuilt-indexes.md
Broke out descriptions into separate page.
> Updated documentation on pre-built indexes

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- os: Ubuntu 18.04.5 LTS
- python: 3.6.9
No issue
> MS MARCO Doc and Passage Replication

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- OS: Ubuntu 20.04.1 LTS
- Python 3.6
Doc: 
Passages:
> Local replication of Passage and Doc, via pyserini

- docs/pypi-replication.md
please see results diff in MS MARCO Document Ranking
I think the result I got is too high?
> replicate pypi doc and update result

- docs/pypi-replication.md
Hey @MXueguang - I fixed a lot of issues with previous iteration... can you please replication at both HEAD and also `pyserini==0.10.1.0`?
Thanks!
> Updated PyPI replication for v0.10.1.0

- pyserini/eval/msmarco_doc_eval.py
- pyserini/eval/msmarco_passage_eval.py
- pyserini/eval/trec_eval.py
- pyserini/evaluate_script_info.py
- pyserini/util.py
re https://github.com/castorini/pyserini/issues/310
> Fold evaluation program into pyserini directly

- pyserini/encoded_query_info.py
- pyserini/prebuilt_index_info.py
- pyserini/util.py
brute-force index: https://www.dropbox.com/s/uwwo2xigvhx3bz7/dindex-faissbf-msmarco-passage-20210112-be7119.tar.gz?dl=0
md5:  ca89a411b111d46b7a579f200d3ac1f5
hnsw index: https://www.dropbox.com/s/dsmtv6asjpd9lkc/dindex-hnsw-msmarco-passage-20210112-be7119.tar.gz?dl=0
md5: 732773b80dae174b3d372a56b6a55a0d
query-embedding: https://www.dropbox.com/s/l5ycxuzumi7fkl6/query-embedding-msmarco-passage-dev-subset-20210112-be7119.tar.gz?dl=0
md5: c9398a713ff13e1780ea2aa2747deb2f
> Update prebuilt index info

- requirements.txt
- setup.py
for https://github.com/castorini/pyserini/issues/315
> add transformers dependency

- docs/dense-retrieval.md
- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- pyserini/search/__main__.py
+ Update to use latest (renamed) MS MARCO eval scripts.
+ Added ability to set BM25 parameters in `pyserini.search`.
+ Updated MS MARCO docs to use `pyserini.search`.
> MS MARCO documentation update

- pyserini/encoded_query_info.py
recreate query embedding pickle file from py36
> update re pickled query embedding info

- docs/working-with-cord19.md
- os: macOS Big Sur 11.01
- python: 3.8.2
- the script is now under scripts folder
- only edges.csv was generated
> updated cord19 docs and added replication log

- docs/pypi-replication.md
- pyserini/eval/msmarco_doc_eval.py
- pyserini/eval/msmarco_passage_eval.py
- pyserini/eval/trec_eval.py
- pyserini/search/__init__.py
- pyserini/search/_base.py
- tests/test_load_qrels.py
- tests/test_load_topics.py
haven't update doc and add unittest yet, will do it in next commit
> add get_qrels

- docs/dense-retrieval.md
- pyserini/dsearch/__main__.py
- pyserini/hsearch/__main__.py
- pyserini/search/__main__.py
re https://github.com/castorini/pyserini/issues/302
Now the hybrid search command looks like:
```bash
python -m pyserini.hsearch   dense --index msmarco-passage-tct_colbert-bf \
--batch 36 --threads 12 \
--encoded-queries msmarco-passage-dev-subset-tct_colbert  \
sparse --index msmarco-passage-expanded \
fusion --alpha 0.24 \
run  --topics msmarco_passage_dev_subset \
--output runs/run.msmarco-passage.tct_colbert.bf.doc2queryT5.tsv \
--msmarco
```
> redesign hybrid search parameter

- docs/dense-retrieval.md
- scripts/dpr/evaluate.py
This is for updating the evaluation script.
will update details about dpr replication results in next PR
> Update dpr evaluation script

- docs/experiments-dpr.md
- docs/experiments-tct_colbert.md
- pyserini/dsearch/__main__.py
- pyserini/hsearch/__main__.py
- pyserini/search/__main__.py
put `--batch-size` and `--threads` to argument under `run` group
> fix hybrid parameters

- docs/experiments-tct_colbert.md
@MXueguang we're missing one condition - doc, hybrid with no expansions. After this gets merged, can you add that one in?
> Cleanup of TCT-ColBERT replication guide

- requirements.txt
- setup.py
fix to get compatible with pygaggle and working on CC
> fix transformers to 4.0.0

- docs/experiments-dpr.md
- docs/experiments-tct_colbert.md
- integrations/test_simpledensesearcher_check_dpr.py
- integrations/test_simpledensesearcher_check_msmarco.py
Truncated regression comparisons to 4 digits, minor documentation tweaks.
Running regressions, not ready for review or merging yet.
> Dense retrieval regression test cases + doc update

- docs/pypi-replication.md
Verified to work on v0.11.0.0.
> Updated PyPI replication docs

- docs/experiments-dpr.md
- integrations/test_simpledensesearcher_check_dpr.py
> Make DPR documentation consistent: --batch vs. --batch-size

- docs/experiments-ance.md
- pyserini/dsearch/__main__.py
- pyserini/dsearch/_dsearcher.py
- pyserini/eval/convert_trec_run_to_dpr_retrieval_run.py
- pyserini/hsearch/__main__.py
- pyserini/prebuilt_index_info.py
- scripts/ance/encode_corpus_msmarco_doc.py
- add ANCE for msmarco-doc ranking
- add back `encoded-queries` option, (but not break current setting)
haven't added encoded queries for ANCE yet, will do in next PR.
> Add ANCE for msmarco-doc ranking

- pyserini/prebuilt_index_info.py
Added more indexes to https://git.uwaterloo.ca/jimmylin/anserini-indexes/-/tree/master
> Add mirrors of pre-built indexes

- scripts/check_download_links.py
Successfully runs:
```
python scripts/check_download_links.py --gitlab --url https://git.uwaterloo.ca/jimmylin/anserini-indexes/-/raw/master/README.md
python scripts/check_download_links.py --vault --url https://git.uwaterloo.ca/jimmylin/anserini-indexes/-/raw/master/README.md
```
> Update script to check Dropbox, GitLab, and CS Vault links

- integrations/test_tct_colbert_encoded.py
Otherwise, we'd get test failures...
> Increased TCT-ColBERT tolerance for running on macOS

- docs/experiments-elastic.md
> Updated Elasticsearch replication log

- scripts/dpr/interpolate_runs.py
a lazy fix.
will try to optimize it later
> fix bug in interpolate script for dpr

- docs/experiments-sbert.md
- pyserini/dsearch/__init__.py
- pyserini/dsearch/__main__.py
- pyserini/dsearch/_dsearcher.py
Remove SBERTQueryEncoder.
Merge it into AutoQueryEncoder
> merge sbert queryencoder into auto query encoder

- pyserini/dsearch/_dsearcher.py
- pyserini/dsearch/_model.py
- requirements.txt
since its not good to install faiss and pytorch by simple `pip install`
utilize `transformers.file_utils`, check if `faiss/torch` avaliable when needed.
if `faiss/torch` not installed, show a guide to the official installation guidance
> Conda-forge install pyserini

- docs/usage-interactive-search.md
- pyserini/dsearch/__init__.py
- pyserini/dsearch/__main__.py
- pyserini/dsearch/_dsearcher.py
re https://github.com/castorini/pyserini/issues/429
> change query encoder class name

- README.md
- docs/experiments-20newgroups.md
- docs/experiments-ance.md
- docs/experiments-distilbert_kd.md
- docs/experiments-dpr.md
- docs/experiments-elastic.md
- docs/experiments-kilt.md
- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- docs/experiments-robust04.md
- docs/experiments-sbert.md
- docs/experiments-tct_colbert.md
- docs/pypi-reproduction.md
- docs/reproducibility.md
- docs/working-with-cord19.md
- project-description.md
https://www.acm.org/publications/policies/artifact-review-and-badging-current
Latest ACM policy has "reproduce" and "replicate" swapped in mean. Bring terminology in repo up to day.
> Replicate -> Reproduce per latest ACM policy

- scripts/encode_queries.py
re https://github.com/castorini/pyserini/issues/456
> encode queries script

- LICENSE.txt
> Add Apache 2 License text

- requirements.txt
we don't need TensorFlow for dense retrieval since we use PyTorch.
> remove tensorflow dependency

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
OS: Ubuntu 20.04.2 LTS (focal)
passage (different): 
```
map                   	all	0.1986
recall_1000           	all	0.8492
```
doc:
```
map                   	all	0.2770
recall_100            	all	0.8076
```
> finished replication

- tests/test_tokenize_json.py
for issue https://github.com/castorini/pyserini/issues/469
but actually, it's weird I cannot reproduce those errors locally even in a refreshed repo. I am not sure if this is gonna fix for test_bert_dir error
> tokentest fix for issue

- pyserini/dsearch/_model.py
PR to fix the issue mentioned in #382 [comments](https://github.com/castorini/pyserini/issues/382#issuecomment-817376103)
> Fix quotes in ignore_keys for ANCE Encoder

- docs/experiments-dpr.md
point to pygaggle doc for e2e part.
> Update dpr doc

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Ran both experiments on Ubuntu in Windows. No problem occurred.
> calvin's replication

- pyserini/prebuilt_index_info.py
- tests/test_index_download.py
re https://github.com/castorini/pyserini/issues/468
> change index download unittest with cacm corpus

- pyserini/encoded_query_info.py
update to latest Anserini fat jar file and then regenerate encoded queries for failed tests
> fix encoded queries inconsistancy

- tests/test_tokenization.py
I coded up tokenization examples mentioned in the book for easy future reference.
> Add tokenization examples in ptr4tr book

- pyserini/eval/msmarco_doc_eval.py
- pyserini/eval/msmarco_passage_eval.py
- pyserini/eval/trec_eval.py
in Windows there is something in stderr too but doesn't influence the stdout.
If should be fine to print both,
> change stdout of eval script

- docs/experiments-ance.md
> Reproduction of ANCE experiments

- pyserini/query_iterator.py
- pyserini/search/_base.py
- tests/test_topics_order.py
re https://github.com/castorini/pyserini/issues/511
> fix topics order and add test

- pyserini/search/_base.py
- tests/test_load_topics.py
re https://github.com/castorini/pyserini/issues/446
> add topics

- integrations/clprf/test_clprf.py
- integrations/simplesearcher_anserini_checker.py
- integrations/sparse/test_search_pretokenized.py
- integrations/sparse/test_simplesearcher_check_core17.py
- integrations/sparse/test_simplesearcher_check_core18.py
- integrations/sparse/test_simplesearcher_check_robust04.py
- integrations/sparse/test_simplesearcher_check_robust05.py
- pyserini/tokenize_json_collection.py
Primarily to make sure you can run the test cases from inside an IDE (fixed relative paths).
> Refactoring and cleanup of sparse test cases

- pyserini/analysis/_base.py
it was removed in Anserini
re https://github.com/castorini/pyserini/issues/529
> remove freebase analyzer

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Environment: Ubuntu 20.04 on Google Compute Engine (150 GB SSD, 4 vCPUs, 16 GB memory)
No issues encountered.
> Updating Replication Log for MS Marco Experiments for pyserini

- pyserini/demo/msmarco.py
Check it out...
```
$ python -m pyserini.demo.msmarco
Attempting to initialize pre-built index msmarco-passage.
/Users/jimmylin/.cache/pyserini/indexes/index-msmarco-passage-20201117-f87c94.1efad4f1ae6a77e235042eff4be1612d already exists, skipping download.
Initializing msmarco-passage...
>>> where was albert einstein born
1 17.03600 To all who live in the nuclear age, Albert Einstein exemplified the mighty creative ability of the individual in a free society.. 'Disruptive' behaviour Albert Einstein was born on 14 March 1879 to Jewish parents at Ulm, Wurttenburg in Germany.Soon afterwards the family moved to Munich where the young Einstein began his education at the Luitpold Gymnasium.o all who live in the nuclear age, Albert Einstein exemplified the mighty creative ability of the …
```
> Simple MS MARCO interactive demo

- pyserini/query_iterator.py
re https://github.com/castorini/pyserini/issues/550
> read trec topic format from file

- pyserini/search/_base.py
- tests/test_load_topics_qrels.py
re https://github.com/castorini/pyserini/issues/560 and https://github.com/castorini/pyserini/issues/559
> fix topic/qrels & update tests

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Environment: GCP e2-standard-2, Ubuntu 20.04, 2 vCPUs, 8GB memory, 150GB SSD.
All results match the given READMEs.
> MS MARCO doc and passage experiment replication

- docs/experiments-ance.md
- docs/experiments-tct_colbert.md
Environment: Ubuntu 18.04, Intel Xeon E5-2630 v4 CPU, 314GB memory.
All results match the given READMEs.
> MSMARCO DR reproduction

- docs/experiments-ance.md
- docs/experiments-tct_colbert.md
> Update spelling for consistency

- pyserini/index/__main__.py
re https://github.com/castorini/pyserini/issues/568
> index err handle

- requirements.txt
re https://github.com/castorini/pyserini/issues/585 and https://github.com/castorini/pyserini/issues/567
> update tqdm, transformers dependency

- README.md
- docs/installation.md
Adding some documentation to install pyserini on tuna/ocra  as part of #573
> Add doc for tuna

- tests/test_load_topics_qrels.py
re https://github.com/castorini/pyserini/issues/560
> qrels bindings

- pyserini/analysis/_base.py
- Add python parser of analyzers mentioned in [PR 1548 in anserini](https://github.com/castorini/anserini/pull/1548) to address #565
> Add Multilingual analyzers for index and search

- pyserini/dsearch/_dsearcher.py
re https://github.com/castorini/pyserini/issues/547
> init encoder from str

- pyserini/dindex/__init__.py
- pyserini/dindex/__main__.py
- pyserini/dindex/_base.py
integrate dense indexing process into Pyserini.
> add dense indexing feature

- README.md
- docs/installation.md
@saileshnankani take a look also?
> Refactoring of installation instructions

- docs/installation.md
Following this should be able to make pyserini work on CC.
Although dense HNSW still suffering some weird error, but it should be able to unblock the majority of our purpose on CC wrt Pyserini/Anserini.
> add installation guide for CC

- tests/test_index_download.py
The line removed is not useful
> remove useless line in test_download_index

- README.md
- docs/usage-dense-indexes.md
- integrations/resources/sample_queries.tsv
> Updated docs about 'searching own docs'

- pyserini/demo/msmarco.py
Resolves #590 
Adds `/random` to interactive demo to ask a random question from the [dev set](https://github.com/castorini/anserini-tools/blob/7e8dfd286b6bc2913fba4cdc26f463ea2940aca9/topics-and-qrels/topics.msmarco-passage.dev-subset.txt).
Example:
```
>>> /random
question: do artichokes contain niacin
1 713.04468 It contains vitamins which include vitamin C, thiamin, riboflavin, niacin, folate, vitamin B-6,B-12, A, E, D and vitamin K. Artichokes also provide minerals such as calcium, iron, zinc, sodium, potassium, manganese, phosphorus and zinc.
2 712.94623 Artichokes also contain vitamin C which, as well as being well known for its immune-boosting properties, is also directly involved in the formation of a protein known as collagen. Collagen is essential for the health of our skin, …
```
> Add random to demo

- tests/test_tokenization.py
Captured results of Lucene tokenization so we can compare against XLM-R, mBERT, etc.
> Added Lucene tokenization to tests

- pyserini/eval/convert_trec_run_to_dpr_retrieval_run.py
- pyserini/eval/evaluate_dpr_retrieval.py
re https://github.com/castorini/pyserini/issues/646
will ready for review after testing.
> update dpr eval

- pyserini/dsearch/__main__.py
- pyserini/hsearch/__main__.py
re https://github.com/castorini/pyserini/issues/653
> fix hybrid bug

- pyserini/setup.py
> use add_classpath so that other jars can be loaded

- pyserini/analysis/_base.py
Thanks for merging [the pull request for Japanese analyzer in anserini](https://github.com/castorini/anserini/pull/1569).
I also change python parser of analyzers for Japanese in pyserini.
> Change analyzer for Japanese (for pyserini)

- docs/experiments-bpr.md
- pyserini/dsearch/__init__.py
- pyserini/dsearch/__main__.py
- pyserini/dsearch/_dsearcher.py
- scripts/bpr/encode_queries.py
- add bpr replication readme
- add bpr encoder
- add binarydense searcher
> Bpr replication

- pyserini/search/_searcher.py
Updates the set_rm3() method to include the filter terms boolean. Sets the default to be True to match previous operation.
Depends on https://github.com/castorini/anserini/pull/1580
> exposes the filter terms parameter for rm3 (#673)

- pyserini/search/__main__.py
Anserini's `SearchCollection` has this option. It is needed sometimes for TREC-COVID.
> Add remove duplicates option

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
* AWS EC2 t3a.2xlarge instance
* OS: Ubuntu
* 256 GB SSD
* 32GB RAM
* OpenJDK version: 11.0.11
No issues encountered.
> MSMARCO doc/passage reproduction

- pyserini/encode/__init__.py
- pyserini/encode/_base.py
- pyserini/encode/_tct_colbert.py
- pyserini/search/_impact_searcher.py
```
original               2hours    /   1M texts
fast_tok               1.5hours /    1M texts
fast_tok_fp16          1.2hours /    1M texts
fast_tok_fp16_onnx      50 min   /   1M texts
```
To encode with TCT_ColBERT
```
python -m pyserini.encode input --corpus <corpus_jsonl_dir> \
--fields 'url' 'text' 'expand'  \
output --embeddings <output_faiss_dir>  \
--to-faiss    \
encoder --encoder tct_colbert-msmarco.onnx  \
--fields 'text'  \
--batch 16
```
> onnx & fp16 for tct_colbert encoding

- docs/experiments-ance.md
- docs/experiments-distilbert_kd.md
- docs/experiments-distilbert_tasb.md
- docs/experiments-sbert.md
- docs/experiments-tct_colbert-v2.md
- docs/experiments-tct_colbert.md
- integrations/dense/test_ance.py
- integrations/dense/test_distilbert_kd.py
- integrations/dense/test_distilbert_tasb.py
- integrations/dense/test_tct_colbert-v2.py
- integrations/dense/test_tct_colbert.py
I rename regressions on `orca` and my iMac Pro, made some minor adjustments to better match the actual figures produced.
> Minor tweaks to regression numbers and test cases

- docs/experiments-dpr.md
Following #692 - which fixes #689 - changes need to be propagated to the documentation also.
> DPR documentation fix

- docs/experiments-ltr-msmarco-passage-training.md
+ add sanity check to the training process
> add sanity check to LTR training repro guide

- docs/experiments-msmarco-v2.md
- scripts/msmarco_v2/generate_train_triplet.py
- bm25 baselines
- scripts to generate doc and passage training triplet id
~- pointer to capreolus about monobert / maxp repro doc?~
~- pointer to dense / sparse retrieval?~
> Pyserini repro doc for MS MARO v2

- docs/experiments-msmarco-v2-tct_colbert-v2.md
> add msmarcov2-tctv2 exp draft

- docs/experiments-msmarco-v2-unicoil.md
update repro command for trained tct + 0shot unicoil
> update unicoil doc

- docs/experiments-unicoil-tilde-expansion.md
- reproduced on orca
- get exactly same results
> reproduce tilde+unicoil

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Results matched replication document. 
Python version: Python 3.9.2
OS: Ubuntu 20.04.3 LTS
> Update replication log for MS MARCO passage/doc ranking

- docs/experiments-unicoil.md
Finalized location of corpora, etc.
> uniCOIL doc repro

- integrations/dense/test_distilbert_kd.py
- integrations/dense/test_distilbert_tasb.py
- integrations/dense/test_sbert.py
It shouldn't fail the test by warning message.
So removed the assert for stderr.
https://github.com/castorini/pyserini/issues/778#issuecomment-927266731
> fix test error

- tests/test_encoder.py
ref https://github.com/castorini/pyserini/issues/800
> fix bug in unittest

- pyserini/prebuilt_index_info.py
- pyserini/resources/index-metadata/index-msmarco-doc-20201117-f87c94-readme.txt
- pyserini/resources/index-metadata/index-msmarco-doc-expanded-per-doc-20201126-1b4d0a-readme.txt
- pyserini/resources/index-metadata/index-msmarco-doc-expanded-per-passage-20201126-1b4d0a-readme.txt
- pyserini/resources/index-metadata/index-msmarco-doc-per-passage-20201204-f50dcc-readme.txt
- pyserini/resources/index-metadata/index-msmarco-doc-per-passage-slim-20201204-f50dcc-readme.txt
- pyserini/resources/index-metadata/index-msmarco-doc-slim-20201202-ab6e28-readme.txt
- pyserini/resources/index-metadata/index-msmarco-passage-20201117-f87c94-readme.txt
- pyserini/resources/index-metadata/index-msmarco-passage-expanded-20201121-e127fb-readme.txt
- pyserini/resources/index-metadata/index-msmarco-passage-ltr-20210519-e25e33f-readme.txt
- pyserini/resources/index-metadata/index-msmarco-passage-slim-20201202-ab6e28-readme.txt
- pyserini/resources/index-metadata/index-robust04-20191213-readme.txt
- pyserini/resources/index-metadata/index-wikipedia-dpr-20210120-d1b9e6-readme.txt
- pyserini/resources/index-metadata/index-wikipedia-dpr-slim-20210120-d1b9e6-readme.txt
- pyserini/resources/index-metadata/index-wikipedia-kilt-doc-20210421-f29307-readme.txt
Mocking up with @MXueguang and I discussed...
> Consolidating metadata for pre-built indexes

- scripts/validate_prebuilt_indexes.py
fix https://github.com/castorini/pyserini/issues/839
> fix bpr indexes validation

- tests/test_index_reader.py
@yuki617 @stekiri please sign off?
Seems like it's a wrap re: #770! #862 presents a nice solution and has a performance benefit as well!
> Final wrap up of issue #770

- pyserini/prebuilt_index_info.py
need to update doc in separate PR.
> install msmarco-doc-tct_v2 prebuilt index

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
- docs/installation.md
When installing faiss-cpu (in pip installation guide), there were errors when running the unittest.
Fixed the issue by specifying the faiss-cpu version according to this link https://github.com/facebookresearch/faiss/issues/708
Here's the environment
MacOS BigSur version 11.6 (20G165)
MacBook Pro (16-inch, 2019)
Processor: 2.3 GHz 8-Core Intel Core i9
Memory: 16 GB 2667 MHz DDR4
> Log branch

- README.md
- docs/installation.md
- docs/pypi-reproduction.md
> Update installation instructions

- docs/prebuilt-indexes.md
- pyserini/prebuilt_index_info.py
- pyserini/resources/index-metadata/lucene-index.mrtydi-v1.1-arabic.20220108.6fcb89.README.md
- pyserini/resources/index-metadata/lucene-index.mrtydi-v1.1-bengali.20220108.6fcb89.README.md
- pyserini/resources/index-metadata/lucene-index.mrtydi-v1.1-english.20220108.6fcb89.README.md
- pyserini/resources/index-metadata/lucene-index.mrtydi-v1.1-finnish.20220108.6fcb89.README.md
- pyserini/resources/index-metadata/lucene-index.mrtydi-v1.1-indonesian.20220108.6fcb89.README.md
- pyserini/resources/index-metadata/lucene-index.mrtydi-v1.1-japanese.20220108.6fcb89.README.md
- pyserini/resources/index-metadata/lucene-index.mrtydi-v1.1-korean.20220108.6fcb89.README.md
- pyserini/resources/index-metadata/lucene-index.mrtydi-v1.1-russian.20220108.6fcb89.README.md
- pyserini/resources/index-metadata/lucene-index.mrtydi-v1.1-swahili.20220108.6fcb89.README.md
- pyserini/resources/index-metadata/lucene-index.mrtydi-v1.1-telugu.20220108.6fcb89.README.md
- pyserini/resources/index-metadata/lucene-index.mrtydi-v1.1-thai.20220108.6fcb89.README.md
- pyserini/search/_base.py
- tests/test_load_topics_qrels.py
Starting will ar, will fill for remaining languages.
> Add pre-built indexes for Mr.TyDi v1.1

- requirements.txt
+ add spacy 3.0.6 and lightgbm 3.2.1 to the requirement
> requirements update for spacy and lightgbm

- docs/prebuilt-indexes.md
- pyserini/prebuilt_index_info.py
- pyserini/resources/index-metadata/lucene-index.msmarco-v2-doc-full.20220111.06fb4f.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v2-doc-passage-augmented-full.20220111.06fb4f.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v2-doc-passage-augmented-slim.20220111.06fb4f.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v2-doc-passage-augmented.20220111.06fb4f.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v2-doc-passage-full.20220111.06fb4f.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v2-doc-passage-slim.20220111.06fb4f.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v2-doc-passage.20220111.06fb4f.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v2-doc-segmented-full.20220111.06fb4f.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v2-doc-segmented-slim.20220111.06fb4f.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v2-doc-segmented.20220111.06fb4f.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v2-doc-slim.20220111.06fb4f.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v2-doc.20220111.06fb4f.README.md
{doc, doc-segmented, passage, passage-augmented} x {default, slim, full}
> Add pre-built indexes for MS MARCO (V2)

- integrations/clprf/test_clprf.py
- integrations/sparse/test_simplesearcher_check_core17.py
- integrations/sparse/test_simplesearcher_check_core18.py
- integrations/sparse/test_simplesearcher_check_robust04.py
- integrations/sparse/test_simplesearcher_check_robust05.py
Recent refactoring change path location.
> Fix index locations in tests

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Reproduced on ubuntu 20.04 via WSL2 on windows 10
> Reproduction of MS-MARCO passage and document ranking experiments 

- integrations/sparse/test_ltr_msmarco_document.py
- integrations/sparse/test_ltr_msmarco_passage.py
> Fix test failure: TestLtrMsmarcoDocument and TestLtrMsmarcoPassage

- scripts/ltr_msmarco/ltr_inference.py
> silence depre warning for np.object in ltr

- docs/prebuilt-indexes.md
- pyserini/prebuilt_index_info.py
- pyserini/resources/index-metadata/lucene-index.msmarco-v1-doc-full.20220131.9ea315.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v1-doc-segmented-full.20220131.9ea315.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v1-doc-segmented-slim.20220131.9ea315.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v1-doc-segmented.20220131.9ea315.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v1-doc-slim.20220131.9ea315.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v1-doc.20220131.9ea315.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v1-passage-full.20220131.9ea315.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v1-passage-slim.20220131.9ea315.README.md
- pyserini/resources/index-metadata/lucene-index.msmarco-v1-passage.20220131.9ea315.README.md
> Add pre-built indexes for MS MARCO (V1)

- scripts/ltr_msmarco/convert_passage.py
- scripts/ltr_msmarco/convert_passage_doc.py
- scripts/ltr_msmarco/convert_queries.py
This pull request addresses #917
> Cleaned up path appends to current directory

- docs/experiments-deepimpact.md
- docs/experiments-msmarco-v2-unicoil.md
- docs/experiments-spladev2.md
- docs/experiments-unicoil-tilde-expansion.md
- docs/experiments-unicoil.md
Also, tweak commands based on recent refactoring:
pyserini.search -> pyserini.search.lucene
pyserini.index -> pyserini.index.lucene
> Update docs for uniCOIL and other learned sparse models

- integrations/dense/test_encode.py
- integrations/sparse/test_ltr_msmarco_document.py
- integrations/sparse/test_ltr_msmarco_passage.py
- pyserini/demo/dpr.py
- pyserini/demo/msmarco.py
- pyserini/dsearch/__main__.py
- pyserini/dsearch/_dsearcher.py
- pyserini/dsearch/_prf.py
- pyserini/eval/convert_trec_run_to_dpr_retrieval_run.py
- pyserini/hsearch/__main__.py
- pyserini/hsearch/_hybrid.py
- pyserini/search/lucene/__main__.py
- pyserini/search/lucene/tprob/_search_tprob.py
- scripts/compute_doc_length_histogram.py
- scripts/generate_docs_from_prebuilt_indexes.py
- scripts/kilt/anserini_retriever.py
- scripts/msmarco-doc/rerank_with_maxp.py
- scripts/msmarco-passage/lookup_docs_from_qrels.py
- tests/test_index_download.py
- tests/test_search.py
> change import path for search.lucene

- docs/experiments-deepimpact.md
- docs/experiments-spladev2.md
- docs/experiments-unicoil-tilde-expansion.md
- docs/experiments-unicoil.md
Use queries in Pyserini instead of downloading queries from an external source
> Update docs for MS MARCO V1 passage learned sparse models

- pyserini/hsearch/__main__.py
to close https://github.com/castorini/pyserini/issues/1017
> fix hsearch import names

- pyserini/resources/index-metadata/faiss.mrtydi-v1.1-arabic.20220207.5df364.README.md
- pyserini/resources/index-metadata/faiss.mrtydi-v1.1-bengali.20220207.5df364.README.md
- pyserini/resources/index-metadata/faiss.mrtydi-v1.1-english.20220207.5df364.README.md
- pyserini/resources/index-metadata/faiss.mrtydi-v1.1-finnish.20220207.5df364.README.md
- pyserini/resources/index-metadata/faiss.mrtydi-v1.1-indonesian.20220207.5df364.README.md
- pyserini/resources/index-metadata/faiss.mrtydi-v1.1-japanese.20220207.5df364.README.md
- pyserini/resources/index-metadata/faiss.mrtydi-v1.1-korean.20220207.5df364.README.md
- pyserini/resources/index-metadata/faiss.mrtydi-v1.1-russian.20220207.5df364.README.md
- pyserini/resources/index-metadata/faiss.mrtydi-v1.1-swahili.20220207.5df364.README.md
- pyserini/resources/index-metadata/faiss.mrtydi-v1.1-telugu.20220207.5df364.README.md
- pyserini/resources/index-metadata/faiss.mrtydi-v1.1-thai.20220207.5df364.README.md
hey @crystina-z is this clearer? I'll tweak for the rest.
> Update/clarify Mr.TyDi pre-built FAISS index READMEs

- integrations/clprf/test_clprf.py
- integrations/lucenesearcher_anserini_checker.py
- integrations/lucenesearcher_score_checker.py
- integrations/run_lucenesearcher.py
`pyserini.search' -> `pyserini.search.lucene`
> Refactor integration tests

- docs/experiments-vector-prf.md
Add nDCG@10 For TREC DL and MRR@10 For MS MARCO Dev according to TOIS paper second round review.
> Add nDCG@10 and MRR@10 in Results

- integrations/dense/test_encode.py
to fix https://github.com/castorini/pyserini/issues/1051#issuecomment-1055831925
> fix broken test

- docs/experiments-tct_colbert-v2.md
- integrations/dense/test_encode.py
- integrations/sparse/test_ltr_msmarco_document.py
- integrations/sparse/test_ltr_msmarco_passage.py
- integrations/sparse/test_lucenesearcher_check_irst.py
- integrations/sparse/test_simple_fusion_search_integration.py
- integrations/sparse/test_unicoil.py
> Light cleanup of integration test cases

- pyserini/search/lucene/__main__.py
> Automatically set BM25 parameters based on known MS MARCO V1 indexes

- docs/experiments-dkrr.md
- pyserini/encoded_query_info.py
- Added comparison scores from original paper
- Added support for encoded-queries
- Replaced pyserini.dsearch with pyserini.search.faiss
> Update DKRR doc

- docs/experiments-dkrr.md
+ Tweaked output run name to be more consistent with other docs
+ Removed `$` - easier copy and paste
+ Moved dev before test.
> Refactor DKRR docs

- pyserini/search/lucene/_base.py
- tests/test_load_topics_qrels.py
> add unicoil topics 

- docs/experiments-ltr-msmarco-document-reranking.md
- docs/experiments-ltr-msmarco-passage-reranking.md
- docs/experiments-msmarco-irst.md
- integrations/sparse/test_lucenesearcher_check_irst.py
- integrations/sparse/test_lucenesearcher_check_ltr_msmarco_document.py
- integrations/sparse/test_lucenesearcher_check_ltr_msmarco_passage.py
- pyserini/prebuilt_index_info.py
- pyserini/search/lucene/irst/_searcher.py
- pyserini/search/lucene/ltr/__main__.py
+ refactoring code to end-to-end
+ using prebuilt index
+ update docs
+ update unit test
> LTR and IRST end-to-end retrieval refactoring

- tests/test_fusion.py
Moved data from Dropbox to GitLab
> Fix broken URL

- docs/experiments-ltr-msmarco-passage-reranking.md
- pyserini/search/lucene/ltr/__main__.py
- pyserini/search/lucene/ltr/_search_msmarco.py
#1083 fix this issue by adding options for both prebuilt and self built index
> Fix ltr searcher with self-built index bug

- tests/test_encoder.py
- tests/test_index.py
> close open()

- README.md
* integration/resources -> tests/resources
* update pyserini.encode example command line so that it's using our sample docs
* explain more about the "fields" used in pyserini.encode
> update readme for dense encoding docs

- pyserini/eval/evaluate_dpr_retrieval.py
Follow up to #1092
Better implementation.
> Change DPR accuracy reporting to 4 digits: better implementation

- tests/test_search.py
Fixes #1099 
Changed setUp to setUpClass and teardown to tearDownClass.
> Changed setup and teardown to class versions (WIP)

- pyserini/eval/convert_trec_run_to_dpr_retrieval_run.py
> fix import error in pyserini.eval

- docs/experiments-ltr-msmarco-document-reranking.md
- docs/experiments-ltr-msmarco-passage-reranking.md
- docs/experiments-msmarco-irst.md
- integrations/sparse/test_lucenesearcher_check_irst.py
- integrations/sparse/test_lucenesearcher_check_ltr_msmarco_document.py
- integrations/sparse/test_lucenesearcher_check_ltr_msmarco_passage.py
- pyserini/search/lucene/irst/__main__.py
- pyserini/search/lucene/ltr/__init__.py
- pyserini/search/lucene/ltr/__main__.py
- pyserini/search/lucene/ltr/_base.py
- pyserini/search/lucene/ltr/_search_msmarco.py
+ refactoring documentation
+ move query process into ltr/irst
> LTR documentation refactoring

- docs/experiments-ltr-msmarco-passage-reranking.md
+ fix typo
+ change dir to store models
> LTR documentation typo fix

- integrations/sparse/test_lucenesearcher_check_irst.py
+ add doc and doc seg tests with trec topics
> update irst unittest with doc

- tests/test_index.py
> Clean up tmp directories after test

- integrations/clprf/test_clprf.py
- integrations/lucenesearcher_score_checker.py
+ use internal trec_eval
+ change to consistent use of f-strings
> Fix broken clprf regressions

- integrations/dense/test_ance.py
- integrations/utils.py
+ Add explicit parameter for ANCE-prf
+ Add different methods for parsing output of different eval utils
> Fix broken regressions for ANCE

- integrations/dense/test_mrtydi.py
Add test case for mrtydi dense results. as in slack discussion
> mrtydi test (for untied-nq)

- integrations/sparse/test_prebuilt_msmarco_v1_doc.py
- integrations/sparse/test_prebuilt_msmarco_v1_passage.py
- integrations/sparse/test_prebuilt_robust04.py
- integrations/utils.py
+ Robust04 bow baselines
+ MS MARCO v1 doc/passage bow baselines
+ MS MARCO v1 doc/passage d2q baselines
> Add integration tests for baselines using pre-built indexes

- docs/2cr/msmarco-v1-doc.html
- docs/2cr/msmarco-v1-passage.html
- docs/2cr/msmarco-v2-doc.html
- docs/2cr/msmarco-v2-passage.html
- pyserini/resources/msmarco-v1-doc.yaml
- pyserini/resources/msmarco-v1-passage.yaml
- pyserini/resources/msmarco-v2-doc.yaml
- pyserini/resources/msmarco-v2-passage.yaml
- scripts/repro_matrix/generate_html_msmarco.py
- scripts/repro_matrix/msmarco_html_row_v1.template
- scripts/repro_matrix/msmarco_html_row_v2.template
+ Empty rows for better spacing.
+ Prettier rendering of parameters, etc.
> Improve HTML rendering of MS MARCO repro matrix

- scripts/es/check_status.py
- scripts/es/create_es.py
- scripts/es/index_bm25.py
- scripts/es/index_unicoil_update.py
- scripts/es/search_bm25.py
- scripts/es/search_hybrid.py
- scripts/es/search_unicoil.py
add elasticsearch script for unicoil/bm25.
> add es scripts for unicoil

- docs/experiments-elastic.md
Recently changed config for field indexing in Anserini, propagating changes to Pyserini.
> Fix broken ES experiment on MS MARCO doc

- docs/experiments-msmarco-irst.md
I ran through IRST reproduction e2e one more time.
> Add to IRST reproduction log

- docs/experiments-trec2022-fairness-ranking.md
- scripts/trec-fair/convert_trec_fair_2022_data_to_jsonl.py
- scripts/trec-fair/convert_trec_fair_2022_queries_to_tsv.py
- scripts/trec-fair/convert_trec_fair_2022_reldocs_to_qrels.py
Add scripts and documentation guide for reproducing BM25, BM25+RM3 baselines for the TREC 2022 Fair Rankings Track
> Add scripts and docs for TREC Fair 2022

- scripts/es/create_es_ann.py
- scripts/es/index_es_hnsw.py
- scripts/es/search_hnsw_ann.py
we were trying to reproduce the results in https://github.com/castorini/pyserini/blob/master/docs/experiments-sbert.md
we current scripts, we get:
> add es script hnsw

- pyserini/search/lucene/_impact_searcher.py
- pyserini/search/lucene/_searcher.py
- tests/test_analysis.py
- tests/test_analysis_lucene8.py
- tests/test_index_reader.py
- tests/test_index_reader_lucene8.py
- tests/test_querybuilder_lucene8.py
- tests/test_search.py
- tests/test_search_lucene8.py
+ Refactor `SimpleSearcher` and `SimpleImpactSearcher` to adopt snake_case method names.
+ Add test cases for Lucene 8
> Add initial support for Lucene 9

- pyserini/encode/__main__.py
this is for models like miniLM and xlrm-large, where the hidden dimension isn't 768
> add dimension arg to dense encoding

- docs/experiments-msmarco-doc.md
> update reproduction log

- README.md
- docs/2cr/mrtydi.html
- docs/prebuilt-indexes.md
- pyserini/prebuilt_index_info.py
- scripts/generate_docs_from_prebuilt_indexes.py
+ Separated pre-built index info into "current" and "deprecated".
+ Re-generated Mr.TyDi HTML pages.
+ Re-generated pre-built index info pages.
> Mr.TyDi cleanup follow-up

- docs/2cr/msmarco-v1-doc.html
- docs/2cr/msmarco-v1-passage.html
- docs/prebuilt-indexes.md
- integrations/sparse/test_lucenesearcher_check_irst.py
- integrations/sparse/test_prebuilt_robust04.py
- integrations/sparse/test_prebuilt_unicoil.py
- integrations/sparse/test_simple_fusion_search_integration.py
- pyserini/prebuilt_index_info.py
- pyserini/resources/msmarco-v1-doc.yaml
- pyserini/resources/msmarco-v1-passage.yaml
- pyserini/search/lucene/irst/_searcher.py
- scripts/generate_docs_from_prebuilt_indexes.py
- scripts/repro_matrix/run_all_mrtydi.py
- scripts/repro_matrix/run_all_msmarco.py
- scripts/repro_matrix/utils.py
+ Fix test cases and flaky tests
> Update MS MARCO V1 pre-built indexes to Lucene 9

- integrations/dense/test_ance.py
- integrations/dense/test_distilbert_kd.py
- integrations/dense/test_distilbert_tasb.py
- integrations/dense/test_dpr.py
- integrations/dense/test_kilt.py
- integrations/dense/test_mrtydi.py
- integrations/dense/test_sbert.py
- integrations/dense/test_tct_colbert-v2.py
- integrations/dense/test_tct_colbert.py
+ Increase parallelism
+ Increase tolerance on a flaky test
> Tweak dense integration tests

- docs/2cr/msmarco-v1-doc.html
- docs/2cr/msmarco-v1-passage.html
- docs/2cr/msmarco-v2-doc.html
- docs/2cr/msmarco-v2-passage.html
- integrations/sparse/test_prebuilt_msmarco_v1_doc.py
- integrations/sparse/test_prebuilt_msmarco_v1_passage.py
- integrations/sparse/test_prebuilt_unicoil.py
- pyserini/resources/mrtydi.yaml
- pyserini/resources/msmarco-v1-doc.yaml
- pyserini/resources/msmarco-v1-passage.yaml
- pyserini/resources/msmarco-v2-doc.yaml
- pyserini/resources/msmarco-v2-passage.yaml
- scripts/repro_matrix/generate_html_msmarco.py
- scripts/repro_matrix/run_all_beir.py
- scripts/repro_matrix/run_all_miracl.py
- scripts/repro_matrix/run_all_mrtydi.py
- scripts/repro_matrix/run_all_msmarco.py
+ Adjusted parallelism to get faster throughput
+ Fixed test cases
> Various MS MARCO v1 and v2 fixes

- pyserini/demo/miracl.py
- pyserini/demo/templates/miracl.html
An interactive web interface to test queries over MIRACL corpora. The demo is implemented via a lightweight web framework, `flask`.
> MIRACL demo

- tests/test_search.py
> Added test case for batch_search to test prf

- pyserini/search/_base.py
- tests/test_load_qrels.py
Sorry @crystina-z - my previous PR didn't fully pass tests... trying again.
> Fix bug in HC4 tests

- docs/2cr/miracl.html
- pyserini/resources/miracl.yaml
- scripts/repro_matrix/generate_html_miracl.py
- scripts/repro_matrix/run_all_miracl.py
> compress error msg for run_all_miracl

- pyserini/prebuilt_index_info.py
Bug as a result of #1334
Fix stats, but still need to implement validation code
> Fix index stats for recently installed pre-built indexes

- pyserini/search/_base.py
- tests/resources/sample_queries_nonint_qid.tsv
- tests/test_load_topics.py
I still found other "int()" operations in the script _base.py. I've fixed all of them.
> Fix all of int()-->isdigit() in  "_base.py"

- pyserini/index/lucene/_base.py
Ref: https://github.com/castorini/anserini/pull/2024
Arg classes refactored into inner classes.
> Refactor code to go along with Arg refactoring in Anserini

- pyserini/search/faiss/_searcher.py
> not lower() encoder name

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Everything went on well and the experiments were reproduced.
I noticed some "Anserini" in the md may be "Pyserini" and I have changed them in the PR. Please check if the change is correct.
Environment: MacBook Pro (2019), 32GB RAM and 500G SSD, MacOS 12.0.1, JAVA 11.0.9.1, Maven 3.8.6, Python 3.8.15.
> Update reproduction log.

- integrations/dense/test_dpr.py
- pyserini/eval/convert_trec_run_to_dpr_retrieval_run.py
- tests/resources/simple_test_run_convert_trec_run_dpr.trec
- tests/resources/simple_topics_dpr.txt
PR based on https://github.com/castorini/pyserini/issues/1290
> Extend Trec to DPR Run Converter to use Custom Topics 

- docs/experiments-gar-t5.md
Minor fixup:
links to Huggingface NQ and TriviaQA datasets added
> Update Gar-T5 repro readme

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Hardware:
M1 14inch macbook pro
Dev Environment:
JAVA 11.0.2, Maven 3.8.4, Python 3.8.
Followed the guide on https://github.com/castorini/pyserini/blob/master/docs/installation.md#troubleshooting-tips and was able to pass unittests and reproduce the results.
> reproduced replication log on an m1 mac

- README.md
- docs/2cr/odqa.html
- docs/experiments-gar-t5.md
- pyserini/resources/naturalquestion.yaml
- pyserini/resources/triviaqa.yaml
- scripts/repro_matrix/defs_odqa.py
- scripts/repro_matrix/generate_html_odqa.py
- scripts/repro_matrix/odqa_html.template
- scripts/repro_matrix/odqa_html_table.template
- scripts/repro_matrix/odqa_html_table_row.template
- scripts/repro_matrix/run_all_odqa.py
- scripts/repro_matrix/utils.py
> ODQA Retrieval 2cr

- scripts/dpr/wiki_generate_tsv.py
> Fix typo in wiki_generate_tsv.py

- integrations/papers/test_ecir2023.py
> Add integration tests for ecir2023

- docs/2cr/odqa.html
- scripts/repro_matrix/generate_html_odqa.py
- scripts/repro_matrix/run_all_odqa.py
Updates
- change output results from 3 decimal point to 2 decimal point
- change output file from `hits=topk` to `hits-topk`
- add linebreak for `bm25` arguments on the frontend display
- beautify some inconsistent use of space before `\` on the frontend display
> minor fixup

- docs/2cr/miracl.html
- pyserini/prebuilt_index_info.py
- pyserini/resources/miracl.yaml
- scripts/repro_matrix/defs_miracl.py
- scripts/repro_matrix/generate_html_miracl.py
- scripts/repro_matrix/run_all_miracl.py
> miracl yo, de pft-then-ft-all; hybrid 2cr for all

- pyserini/search/faiss/__main__.py
Add `contriever` to command line `encoder-line` options.
> add contriever to command line argument

- integrations/sparse/test_lucenesearcher_check_ltr_msmarco_document.py
> Increase tolerance for flaky LTR test

- scripts/repro_matrix/run_all_miracl.py
> Increase tolerance for flaky MIRACL tests

- pyserini/encode/__main__.py
mean pooling of representations added when encoding via Contriever. For encoding queries, this is already done: https://github.com/castorini/pyserini/blob/e40d4a3770d0d4639425b7cc6c348112e26f89a9/pyserini/search/faiss/__main__.py#L131
> Contriever encode issue resolved

- scripts/repro_matrix/run_all_beir.py
The line of average is repeating, need to move it out of the for-loop block.
> Fix avg repeating

- scripts/repro_matrix/run_all_beir.py
Fix `run_all_beir` output alignment
> Fix contriever alignment

- tests/test_prebuilt_index.py
Issues http head requests to make sure we're getting response code 200
> Add test case to sanity check pre-built indexes

- pyserini/search/_base.py
- Fixed functions for getting qrels.
- Unittest passed after the fix
> fix search._base for topics and qrels integration

- pyserini/search/lucene/__main__.py
- pyserini/search/lucene/_impact_searcher.py
- tests/test_encoder.py
Usage
```bash
python -m pyserini.search.lucene \
--index ../anserini/indexes/lucene-index.msmarco-passage-splade-pp-ed \
--topics msmarco-passage-dev-subset \
--output runs/test.tsv \
--batch 36 --threads 12 --hits 1000 --impact \
--onnx-encoder <onnx-encoder name e.g., 'SpladePlusPlusEnsembleDistil'> 
```
[Related PR](https://github.com/castorini/anserini/pull/2113)
> add onnx encoder integration

- docs/2cr/mrtydi.html
- pyserini/2cr/mrtydi.py
> Minor tweak for Mr.TyDi 2CR

- docs/2cr/miracl.html
- docs/prebuilt-indexes.md
- pyserini/2cr/miracl.py
- pyserini/2cr/miracl.yaml
- pyserini/prebuilt_index_info.py
- pyserini/resources/index-metadata/faiss.miracl-v1.0.20230313.e40d4a.mcontriever-tied-pft-msmarco.README.md
> mContriever on MIRACL

- tests/test_prebuilt_index.py
quick fix of the test case related to #1544
> mcontriever fix test

- pyserini/demo/acl.py
- pyserini/demo/templates/acl.html
- pyserini/demo/templates/assets/acl-logo.svg
- Added a web server that demonstrates retrieval from the `ACL anthology` dataset
- Followed through steps to generate `ACL` index from [working-with-acl-anthology.md](https://github.com/billcui57/pyserini/blob/master/docs/working-with-acl-anthology.md)
- Copy pasted the generated index into `Pyserini` `/indexes` directory
- Created web server that points `Lucene` at that index
- Only sparse search was used. I.e this demo is only backed by `LuceneSearcher`
- Multiple languages not supported
> Added acl lucene demo

- docs/2cr/miracl.html
- pyserini/2cr/miracl.py
- pyserini/2cr/miracl.yaml
quick fix on the bugs in miracl 2cr
waiting for `python -m pyserini.2cr.miracl --condition mcontriever-tied-pft-msmarco --language $lang --display-commands` finishing on all languages.
> Miracl 2cr fix

- pyserini/encode/__main__.py
- pyserini/encode/_base.py
- `--docid-field` argument added for custom docid field names.
- `_id` added to default names as well.
> custom docid field added to pyserini.encode

- docs/experiments-msmarco-doc.md
- docs/experiments-msmarco-passage.md
Big addition is the interactive retrieval section.
> Refactor + augment onboarding docs for MS MARCO passage

- docs/experiments-msmarco-passage.md
This cl:
- Adds qrel conversion commands 
- Adds `sahel-sh` to repo log for ` experiments-msmarco-passage.md`
> Update experiments-msmarco-passage.md with qrel conversion

- docs/conceptual-framework.md
This cl adds repro log for `sahel-sh` to `conceptual-framework.md`
> Update conceptual-framework.md with repro log

- docs/conceptual-framework.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
@sahel-sh can you try running through this next lesson?
Like before, CR to provide comments, and then a separate PR to add to repro log.
> Next onboarding lesson: NFCorpus

- docs/conceptual-framework.md
- docs/experiments-nfcorpus.md
hi @sahel-sh - in rereading previous guide, it seems like I forgot to add an explicit "next" pointer.
> Add link to connect onboarding path

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Environment:
Ubuntu 22.04 on student environment.
Issues:
Found there were issues with the dense retrieval on 11.5 gb of RAM, so linux virtual machine on a windows laptop with 16gb RAM could not work. Good news is the entire onboarding to this point works on the student environment for any future Waterloo student that doesn't have more than 12 gb RAM on their local computer. When running dense retrieval, CPU times out by default so you actually have to use the command `ulimit -t unlimited` to get it going.
> Reproduction of Pyserini Onboarding

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-nfcorpus.md
Apple MacBook m1
Environment details
Conda version: 23.7.2 
Java: 11.0.9.1
mvn: 3.9.4
Python: 3.8.17
I was able to reproduce regenerate the results and everything worked as expected.
> Adds reproduction logs for the onboarding path steps (4-6)

- README.md
- docs/installation.md
PR for #1611
Added the solution for M1/M2 issues in #1599 and #1607.
> Refactored Installation Guide

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
**OS & Hardware**: Student Environment (Ubuntu2204)
**Result**: I was able to replicate the Tour and understanding the content.
**Hiccups**: When doing pyserini development installation:
- If Java 11+ was used to install [anserini](https://github.com/castorini/anserini), don't install Maven with conda.
- This is because conda installed Maven forces you (at least for me) to use Java 8, which will cause a lot of tests generating errors using its fatjar.
**Fix**(what I did):
Simply skip the install Maven step
> Adding Logs for Onboarding path steps (3-6)

- pyserini/encode/_splade.py
- tests/test_encoder.py
> fix #1625 and add test case

- docs/2cr/msmarco-v1-passage.html
- pyserini/2cr/msmarco-v1-passage.yaml
- pyserini/2cr/msmarco.py
> Add 2CR for SPLADE++ runs with PyTorch

- pyserini/2cr/miracl.yaml
- pyserini/2cr/mrtydi.yaml
> Fix MIRACL and Mr. TyDi 2CR failures

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Using MacBook Pro 2019 running macOS Ventura 13.4.1
Everything worked fine with no issues. Some commands took a while due to slow Internet and slow processor, but this was to be expected.
> Add to reproduction log by @lucedes27

- docs/2cr/miracl.html
- docs/2cr/mrtydi.html
Fix MIRACL and Mr. TyDi 2CR failures described in #1631 - generate new docs
> Generate new 2CR docs after MIRACL/Mr.TyDi fix

- docs/2cr/beir.html
- pyserini/2cr/beir.py
To stay consistent with formatting
> Replace dots with dashes in BeIR 2CR runfiles

- pyserini/eval/trec_eval.py
As described in #1658 - changing the csv read engine to 'python' seems to fix the issue. Rerunning all regressions to confirm.
> Fix for BEIR regression failure described in #1658

- docs/2cr/odqa.html
- pyserini/2cr/odqa.py
Also changes `--topics` to `--topic` in odqa 2cr
> Update threads and batch_size for odqa 2CR

- pyserini/search/faiss/_searcher.py
This commit allows duplicate documents to be removed from final dense search results
> add remove_dups argument for dense retrieval

- pyserini/search/faiss/_searcher.py
Reverts castorini/pyserini#1510
> Revert "add remove_dups argument for dense retrieval"

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Setup
- OS: Windows 11 + Windows WSL2 (Ubuntu)
- Java: openjdk version "11.0.20.1" 2023-08-24
- Maven: Apache Maven 3.9.2
- Python: Python 3.8.18
Results
- Successfully reproduced all the records mentioned in the docs
Issues
- Unable to directly access Huggingface.co and raw.githubusercontent.com from some regions, (e.g. mainland China)
- I found the following article [https://zhuanlan-zhihu-com.translate.goog/p/153124468?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp](url) helpful for WSL users. It provides simple steps for setting up a global proxy.
> Update onboarding docs

- pyserini/2cr/beir.py
- pyserini/2cr/miracl.py
- pyserini/2cr/mrtydi.py
- pyserini/2cr/msmarco.py
- pyserini/2cr/odqa.py
@jasper-xian I think a light review is sufficient. I've verified that the 2CRs still run from my end.
> De-lint + minor refactoring for PEP8 compliance

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
> Add to onboarding reproduction logs

- pyserini/2cr/miracl.py
- pyserini/2cr/miracl.yaml
- pyserini/2cr/mrtydi.yaml
Reverts castorini/pyserini#1632
> Revert "Fix MIRACL and Mr. TyDi 2CR failures"

- pyserini/search/hybrid/__main__.py
- requirements.txt
Addresses bug in #1699 
Also adds requirements for #1622
> Fix max_length bug for hybrid search

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
I successfully completed all the steps in this stage without any issues. In some steps, as I was using the Windows operating system, I had to adapt certain commands to be compatible with this operating system to ensure they executed correctly. Attached are some images of the completed steps.
> experiments-msmarco-passage: Done

- pyserini/2cr/msmarco.py
Minor changes to scores with latest packages.
> Recalibrate scores for Apple's M1 Processor with new package upgrades

- pyserini/encode/__main__.py
- pyserini/encode/_auto.py
- pyserini/encode/query.py
- pyserini/search/faiss/__main__.py
https://github.com/castorini/pyserini/issues/1720
> config pooling and l2norm for autoencoder

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
**Operating System**
macOS Ventura version 13.5
**Development Environment (from conda)**
Python: Version 3.10.13
Java: Version 11.0.13
Apache Maven: Version 3.9.5
 
**Hardware**
RAM: 24 GB
Storage: 512GB SSD
Processor: Apple M2
 
**Execution results**
Initially experienced some problems when installing the nmslib, following the command provided by *pratyushpal* in this [pull-request](https://github.com/castorini/pyserini/pull/1570) led me to the same problem as *labaran1* had. Later, I found this [discussion](https://github.com/pybind/pybind11/discussions/4333) online, indicating there's a known error between python3.11 and certain versions of pybind11. Therefore I used a conda environment for better dependency control and changed the python version from 3.11.x to 3.10.x. Everything …
> Add entries to reproduction log - Yifei

- docs/2cr/miracl.html
- docs/2cr/mrtydi.html
- docs/2cr/msmarco-v1-passage.html
- pyserini/2cr/msmarco-v1-passage.yaml
- pyserini/2cr/msmarco.py
- pyserini/2cr/msmarco_html_v1_passage.template
- pyserini/prebuilt_index_info.py
- tests/test_prebuilt_index.py
Updated docs as well...
Currently doesn't work - @MXueguang will coordinate with @ArthurChen189 to fix.
> Add cosDPR-distil OTF 2CR

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
See: https://github.com/castorini/pyserini/issues/1733
> Add reproduction results by sueszli

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Results for Pyserini were reproduced on 2023-12-14, and **everything worked**.
- Operating System: Ubuntu 22.04.3 LTS
- Python: 3.10.12
- Java: 11.0.21 2023-10-17
- Maven: 3.6.3
> add reproduction logs

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
- Python 3.10.13
- Java 11.0.13
- Maven 3.9.6
- Conda 2.5.0
- Model Name: MacBook Pro
- System Version: macOS 13.4.1 (c)
- Chip: Apple M1 Pro
- Total Number of Cores: 8 (6 performance and 2 efficiency)
- Memory: 16 GB
able to generate all the outputs
https://github.com/castorini/pyserini/blob/0f5db95dbd5ed6b983ac4f638b486a70bc5ea99a/docs/experiments-msmarco-passage.md?plain=2#L36 was tiny confusing for me as if it would be applicable to all stages or not so I ended up modifying the path :
```
(pyserini) ➜  msmarco-passage git:(paniz-onboarding) python -m pyserini.index.lucene \
--collection JsonCollection \
--input collection_jsonl \
--index indexes/lucene-index-msmarco-passage \
--generator DefaultLuceneDocumentGenerator \
--threads 9 \
--storePositions --storeDocvectors --storeRaw
```
> add production log

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
All of the tests and commands worked as described for me.
macOS Monterey
Python Version: Python 3.9.6
Apache Maven 3.9.6
Apple M2 Chip
8GB RAM 256 GB SSD
> Add reproduction logs to onboarding

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
https://github.com/castorini/anserini/pull/2342
Python 3.10.12
> Add onboarding reproduction logs

- data_munging.py
- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
[castorini/anserini#2345](https://github.com/castorini/anserini/pull/2345)
Python 3.10.12
> Added onboarding reproduction logs

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Python 3.10.13
Java 11.0.22
Maven 14.2.1
MacOS Sonoma
M2
Had some problems with Faiss package, resolved with this issue
https://github.com/facebookresearch/faiss/issues/2868#issuecomment-1555426724
> Add to reproduction log

- docs/prebuilt-indexes.md
- pyserini/prebuilt_index_info.py
- pyserini/resources/index-metadata/faiss.ciral-v1.0.afriberta-dpr-ptf-msmarco-ft-latin-mrtydi.20240212.2154e7.README.md
- pyserini/resources/index-metadata/faiss.ciral-v1.0.mdpr-tied-pft-msmarco.20240212.2154e7.README.md
- pyserini/resources/index-metadata/lucene-index.ciral-v1.0-en.20240212.2154e7.README.md
This PR includes:
- English prebuilt indexes
- DPR prebuilt indexes
> Add prebuilt indexes for ciral

- README.md
- docs/2cr/ciral.html
- pyserini/2cr/ciral.py
- pyserini/2cr/ciral.yaml
- pyserini/2cr/ciral_html.template
- pyserini/prebuilt_index_info.py
- pyserini/search/_base.py
This PR includes:
- 2cr documentation for ciral
- Adding JQrels and JTopics for ciral
- Tools submodule update
> Add 2cr for CIRAL

- tests/test_prebuilt_index.py
Adding prebuilt index tests for ciral.
> Add prebuilt index tests for ciral

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Used UWaterloo Student Servers again
CPU: Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
RAM: 384GB
Environment:
Ubuntu 22.04.3 LTS
Python 3.10.12
Java 11.0.21
Apache Maven 3.6.3
Failing a single unit test as communicated earlier in email:
test_bm25_vectorizer_train
> Updated Onboarding docs

- pyserini/2cr/msmarco.py
This cl cleans up msmarco 2cr. dl22 will be added in a follow up cl
> Update msmarco 2cr

- tests/test_prebuilt_index.py
Needed to increment after commit https://github.com/castorini/pyserini/commit/442e7e1026728f29cc3a9d3e684c561637ad1d7b
> Increment number of MS MARCO faiss indexes in test

- docs/2cr/msmarco-v2-doc.html
- docs/2cr/msmarco-v2-passage.html
- pyserini/2cr/msmarco-v2-doc.yaml
- pyserini/2cr/msmarco-v2-passage.yaml
- pyserini/2cr/msmarco.py
- pyserini/2cr/msmarco_html_row_v2.template
- pyserini/2cr/msmarco_html_v2_doc.template
- pyserini/2cr/msmarco_html_v2_passage.template
This cl adds 2cr for dl22,
`RR@100` and `R@100` metrics for dl21 are removed to make room for dl22
> add 2cr for dl22

- docs/2cr/ciral.html
- pyserini/2cr/ciral.py
- pyserini/2cr/ciral.yaml
Corrected the AfriBERTa-DPR index names.
All results are successfully reproduced.
> Modify ciral 2cr

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Hardware:
CPU: Apple M1 Pro
RAM: 16GB
Environment:
macOS Monterey (V12)
Python 3.10.12
Java 11.0.21
Apache Maven 3.9.6
Was able to reproduce without any issue from the terminal.
> Add to onboarding reproduction logs 

- pyserini/2cr/atomic.py
- pyserini/2cr/beir.py
- pyserini/2cr/ciral.py
- pyserini/2cr/miracl.py
- pyserini/2cr/mrtydi.py
- pyserini/2cr/msmarco.py
- pyserini/2cr/odqa.py
This cl fixes issue https://github.com/castorini/pyserini/issues/1808
TESTED=Generating reports from all modified .py 2cr files works
> replace deprecated pkg_resources with importlib.resources

- pyserini/2cr/beir.py
- pyserini/2cr/beir.yaml
- pyserini/2cr/miracl.py
- pyserini/2cr/mrtydi.py
- pyserini/2cr/mrtydi.yaml
- pyserini/2cr/msmarco-v1-passage.yaml
- pyserini/2cr/msmarco.py
- scripts/jobs.regressions-all.txt
Recalibrate 2CR scores wrt new dependencies.
> Refactor 2CR

- pyserini/prebuilt_index_info.py
Updated CIRAL's index info to that of the corrected files.
> Update index info

- integrations/dense/test_dpr.py
I'm getting small differences on my Mac Studio.
> Increase test tolerance due to OS differences, dependency versions, etc.

- pyserini/search/faiss/__main__.py
- tests/test_hybrid_search.py
Fix issue #1830
Add test case for hybrid searcher on beir arguana
> address multimodal dense_searcher compatibility for hybrid_searcher

- pyserini/index/faiss.py
> Fix faiss indexing bug

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Configuration:
Processor Speed (Max): 1800 MHz
Memory (RAM): 16 GB
Processor: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (GenuineIntel)
Operating System: Microsoft Windows 10 Pro (64-bit)
Number of Cores: 4
Number of Logical Processors: 8
Initially, I tried to solve the problems associated with the repo Pyserini using PowerShell and converting the scripts to PowerShell format for Windows. However, I encountered a few issues while running on Windows. For instance, installing nmslib on Windows was causing errors. Besides, installing trec_eval was also an issue, which I solved by conducting tasks for the previous repo, Anserini. I used virtualization on my computer using WSL (Ubuntu 22.04.4) and I was easily able to reproduce all the results. Additionally, I had some issues with my computer …
> Update Reproduction Logs

- docs/2cr/beir.html
- docs/2cr/msmarco-v1-passage.html
This cl runs the following to update all 2cr reports if needed:
```
python -m pyserini.2cr.msmarco --collection v1-passage --generate-report --output docs/2cr/msmarco-v1-passage.html
python -m pyserini.2cr.msmarco --collection v1-doc     --generate-report --output docs/2cr/msmarco-v1-doc.html
python -m pyserini.2cr.msmarco --collection v2-passage --generate-report --output docs/2cr/msmarco-v2-passage.html
python -m pyserini.2cr.msmarco --collection v2-doc     --generate-report --output docs/2cr/msmarco-v2-doc.html
python -m pyserini.2cr.miracl --generate-report --output docs/2cr/miracl.html
python -m pyserini.2cr.mrtydi --generate-report --output docs/2cr/mrtydi.html
python -m pyserini.2cr.beir   --generate-report --output docs/2cr/beir.html
python -m pyserini.2cr.odqa   --generate-report …
```
> Regenerate all 2cr reports

- docs/2cr/beir.html
- pyserini/2cr/beir_html.template
- pyserini/2cr/ciral.py
- scripts/jobs.integrations-all.txt
- tests/test_prebuilt_index.py
+ Updated BEIR 2CR docs to provide refs and more detailed execution instructions.
+ Fixed broken test cases.
+ Tweaked 2CR regressions; minor refactoring.
> Update BEIR 2CR docs; other minor touch-ups

- pyserini/prebuilt_index_info.py
Fixes path issues with prebuilt index tarfiles
> Fix BEIR Cohere-embed-english-v3.0 tarfiles

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
**Environment Details:**
-**Operating System: Ubuntu 22.04.4 LTS**
-**System RAM: 24GB**
**Experience:**
The process was smooth with no significant issues, except for the wget command for downloading the dataset not functioning as expected. I utilized the wget command from the Anserini documentation, which worked without issue. The scripts ran flawlessly after setting up the environment correctly, and the step-by-step guidance was clear and easy to follow.
> I have created the new pull request do to the issues

- requirements.txt
> requirements update with safer pybind11

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Successfully reproduced results for the experiments on Macbook Pro M3 8GB.
> Update experiments-msmarco-passage.md reproduction log Sean Song

- pyserini/encode/__main__.py
Solution for the issue #1911  and #1907
> Included contriever encoder-class type for proper document encoding

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
OS: Ubuntu 20.04 on WSL2
Java: JDK 21
Maven: Maven 3.9.7
Python: Python 3.10
Status:
I successfully followed the guide and reproduced the results easily. The concepts were familiar to me due to my background in information retrieval. Although I hadn't worked with Pyserini before, it was a great experience.
> Completed Foundations of Retrieval Onboarding Path

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Successfully reproduced "experiments-msmarco-passage", "conceptual-framework", "experiments-nfcorpus", and "conceptual-framework2"
Device information:
macOS version 14.5
MacBook Pro (Sonoma, 16-inch, 2019)
Processor: 2.4 GHz 8-Core Intel Core i9
Memory: 32 GB 2667 MHz DDR4
Graphics: Intel UHD Graphics 630 1536 MB
> add to reproduction logs

- docs/2cr/beir.html
- pyserini/2cr/beir.py
- pyserini/2cr/beir_html.template
Brought the cqadupstack rows in the BEIR 2CR into a separate table. Created an averaged row in the main table.
> Seperate cqadupstack rows in BEIR 2CR

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
I’ve successfully completed the Pyserini onboarding process. It was a great experience, and I learned a lot about BM25 retrieval and dense retrieval models. Although I encountered some challenges, like the extended time required for indexing, the overall experience was enriching and informative.
> walking through all the onboarding path

- integrations/clprf/test_clprf.py
- integrations/sparse/test_lucenesearcher_check_irst.py
- integrations/utils.py
- pyserini/eval/trec_eval.py
- pyserini/pyclass.py
- tests/resources/simple_trec_run_unjudged_keep.txt
- tests/resources/simple_trec_run_unjudged_remove.txt
- tests/test_trectools.py
trec_eval is already bundled with Anserini. Also, clean up trec_eval output - i.e., not so noisy.
> Switch from using jtrec_eval to trec_eval

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Run on Windows 11 WSL 2 with Ubuntu 22.04. 
Hardware: 5600x 32GB ram with 3060ti 8GB of VRAM.
> Reproduction logs + minor suggestions

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Windows OS with conda environment. no problem running everything in WSL.
> Add to onboarding reproduction logs (#1995)

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Software: Ubuntu 22.04, Conda, Python 3.10
Hardware: Dell g5 5587, core i7 8th gen, 16 GB RAM, 1050ti 4GB VRAM
It all worked after installing the missing packages.
> Add Onboarding Logs

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
setup: macOS, Apple M2
everything worked
> added to reproduction logs

- docs/experiments-dpr.md
- docs/experiments-tct_colbert-v2.md
- docs/experiments-tct_colbert.md
Follow up to #2003
Finished refactoring docs for dpr, tct1, and tct2
> Refactoring documentation for some dense models

- docs/experiments-ance.md
- docs/experiments-bpr.md
- docs/experiments-distilbert_kd.md
- docs/experiments-distilbert_tasb.md
- docs/experiments-dkrr.md
- docs/experiments-dpr.md
- docs/experiments-sbert.md
- docs/experiments-tct_colbert-v2.md
- docs/experiments-tct_colbert.md
Follow up to #2003 and #2004 - verifying old dense retrieval experiments.
Sets us up to start tackling #1728
> Repro of dense retrieval experiments

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Completed the onboarding on MacOS (MacBook Pro M1)
Everything worked as expected.
> Added to Reproduction Logs (Pyserini) - Raghav Vasudeva

- pyserini/search/lucene/_searcher.py
- tests/test_search.py
- tests/test_search_lucene8.py
First pass on patch and tests to address #1999.
> Fix for JSimpleSearcher method typo in LuceneSearcher

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Hi all,
I am using a Macbook Pro with M2 chip and vscode
some issues I encountered:
1. not all unit tests passed after [development installation](https://github.com/castorini/pyserini/blob/master/docs/installation.md#development-installation), but I guess its fine since I saw a response saying that's ok in a ticket
2. Is IndexReader renamed to LuceneIndexReader?
3. AutoQueryEncoder is in pyserini.encode but the md files sometimes tells user to import from pyserini.search.faiss, I included the fix in this pr
> reproduced tasks for onboarding process

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Completed the Foundations of Retrieval 
System Information:
- Operating System: Windows 10 21H2
- Language: Python 3.12
- Java Version: java 23.0.1
- Hardware Specs: Intel Core i5-11th Gen, 16GB RAM, Iris Xe
> Successfully Reproduced Results

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Environment:
MacOS + Maven 3.9.9 and Java 21
> Add to onboarding repro logs

- docs/prebuilt-indexes.md
- pyserini/prebuilt_index_info.py
- pyserini/query_iterator.py
- tests/test_prebuilt_index.py
General cleanup of both code and docs.
> Refactor code to support Arctic models on MS MARCO v2.1

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Macbook Air M3 (macOS 14.6)
Python 3.10
Java openJDK 21
Maven 3.9.9
I used the Conda environment regarding the issue noted in #2047, and all results were reproduced correctly. Thanks!
> Reproduce Pyserini onboarding task results

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
- docs/installation.md
System: Apple M1 Pro Macbook Pro
OS: MacOS 14.6.1
Python: 3.10
Java: OpenJDK 21.0.5
Maven: 3.9.9
Everything worked well.
Inconsequential typo fix in `docs/installation.md`
> [Onboarding] Added to reproduction logs & tiny typo fix

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
System: Apple M1 Max Macbook Pro 
OS: MacOS Monterey Version 12.2.1
Python: 3.10.16
Java: openjdk 21.0.5
Maven: 3.9.9
Everything worked great!
> Onboarding path: Pyserini

- scripts/validate_prebuilt_indexes.py
- scripts/verify_url_prebuilt_indexes.py
Update scripts for new index types.
> Tweak script to verify/validate indexes

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Environment: UWaterloo CS Student Teaching Hosts
Operating system: Ubuntu 22.04
Python Version: 3.10.13
Followed the linked guide to remove CPU limit, and everything worked.
> Added to reproduction logs for onboarding

- docs/conceptual-framework3.md
Created file for repro for spladev3
System: Macbook Pro M3
Python: 3.11.11
Maven: 3.9.9
Java: openjdk 21.0.6
> added conceptual-framework3.md to onboarding

- docs/2cr/msmarco-v1-passage.html
- docs/prebuilt-indexes.md
- pyserini/2cr/msmarco-v1-passage.yaml
- pyserini/2cr/msmarco.py
- pyserini/2cr/msmarco_html_v1_passage.template
- pyserini/index/lucene/_base.py
- pyserini/prebuilt_index_info.py
- pyserini/resources/index-metadata/lucene-inverted.msmarco-v1-passage.splade-v3.20250329.4f4c68.README.md
- pyserini/search/faiss/_searcher.py
- pyserini/search/lucene/_impact_searcher.py
- pyserini/util.py
- scripts/generate_docs_from_prebuilt_indexes.py
- tests/test_prebuilt_index.py
+ Added symbol bindings for prebuilt indexes: MS MARCO passage using SPLADEv3
+ Added corresponding 2CR (w/ PyTorch)
+ pre-built -> prebuilt
+ IndexReader -> LuceneIndexReader
> Add SPLADEv3 prebuilt indexes

- pyserini/encode/_openai.py
- pyserini/encode/query.py
> Fix typo: OpenAIQueryEncoder -> OpenAiQueryEncoder

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Env
OS: Linux
RAM: 16 GB
Python: 3.10
Java: 21.0.6
Status
results match numbers in the guide
> updated reproduction log

- docs/usage-indexreader.md
Updates documentation for usage-indexreader.md as requested by #2093
> Update documentation for usage-indexreader.md

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
- **Name:** Roselyn Zhang
- **Date:** 2025-05-19
- **Platform:** MacBook Pro, macOS 15.4.1 (24E263), Apple M4 Pro, 24 GB RAM
- Java version: `java -version`  
```
openjdk version "23.0.2" 2025-01-21
OpenJDK Runtime Environment Homebrew (build 23.0.2)
OpenJDK 64-Bit Server VM Homebrew (build 23.0.2, mixed mode, sharing)
```
- python version: ```python --version```
```Python 3.10.14``` !!! **Noted: original default is python 3.13 but has to downgrade to 3.10 in order to pip install pyserini**
-- Result
All outputs match, no issue found.
> pyserini repro log

- docs/experiments-vector-stores.md
> Added Reproduction Log and Code Changes to experiments-vector-stores.md

- pyserini/resources/index-metadata/lucene-inverted.beir-v1.0.0-splade-v3.20250603.168a2df.README.md
Added doc for generating splade-v3 indexes for BEIR datasets
> added doc for BEIR SPLADE-v3 indexes

- pyserini/2cr/atomic.py
- pyserini/2cr/atomic.yaml
- pyserini/2cr/beir.py
- pyserini/2cr/ciral.py
- pyserini/2cr/miracl.py
- pyserini/2cr/mrtydi.py
- pyserini/2cr/msmarco.py
- pyserini/2cr/odqa.py
+ atomic score change
+ msmarco-v1-passge case where observed score is higher than expected - note as OKish, not fail
+ fixed deprecated code
> Light refactoring of 2CRs

- README.md
- docs/usage-interactive-search.md
Don't merge until, well, the customized index handling is merged in Anserini.
Mostly inspired by the original Anserini doc
> Show how to remove indexes

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Everything worked successfully!!
-***OS:*** macOS Ventura 15.5 (Build 24F74) on MacBook Pro
-***Python:*** Python 3.9.13
> Onboarding for Pyserini - Reproduction Logs by @ed-ward-huang

- pyserini/server/mcp/mcpyserini.py
- pyserini/server/mcp/tools.py
- pyserini/server/models.py
- pyserini/server/rest/routes/indexes.py
- pyserini/server/search_controller.py
Fixes #2184 by changing FastMCP import, different ports now work.
Fixes Pydantic models.
> Fix various MCP things

- docs/usage-mcp.md
- docs/usage-rest.md
- pyserini/server/mcp/mcpyserini.py
- pyserini/server/models.py
- pyserini/server/rest/routes/indexes.py
- pyserini/server/search_controller.py
Also cleans up FastAPI server. All the endpoints work.
> Update server documentation

- pyproject.toml
> Update dependencies list for MCP 

- pyserini/eval/trec_eval.py
> Add readable error message for pyserini.eval.trec_eval

- docs/usage-mcp.md
Everything worked and was clear
because I built my conda env in WSL , this configuration worked for me
```
{
"mcpServers": {
"mcpyserini": {
"command": "wsl",
"args": [
"-d", "Ubuntu",   
"--",
"/home/jjgreen/miniconda3/envs/mcpyserini/bin/python",
"-m", "pyserini.server.mcp",    
"--transport", "stdio"     
],
"env": {
"JAVA_HOME": "/usr/lib/jvm/java-21-openjdk-amd64"
}
}
}
}
```
> Add to repro

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
My Setup:
- Device: MacBook Air M3
- OS: macOS 13.5
- JDK: Temurin 11.0.27
- Maven: 3.9.9
I encountered no issues, all steps ran smoothly.
> Add reproduction log entry for 2025-08-24

- pyserini/search/faiss/_searcher.py
The support for dict queries (needed for m-beir and other future multimodal queries) is already added to the fiass simple search in https://github.com/castorini/pyserini/pull/2216.
This cl adds support for dict queries in batch search.
It also handles different embedding shapes gracefully.
> add support for dict queries to fiass batch search

- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
I followed the MS MARCO passage ranking exercise in Pyserini:
- Installed Pyserini and required packages
- Downloaded and prepared the MSMARCO passage dataset
- Ran search and summarization scripts successfully
- Saved results to results.json and converted them to results.csv
- Added my entry to the Reproduction Log in experiments-msmarco-passage.md
Everything worked as expected, and I’ve documented the steps in the log.
> Add my MS MARCO passage ranking reproduction log

- docs/usage-mcp.md
Env:
pip 22.0.2 from python 3.10
fastmcp                   2.12.3
mcp                       1.14.0
I used remote server to run the mcp on both claude and cursor. Both give me same results.
1. 
7157707 (11.01): A New England sandwich of lobster meat on a grilled top‑split hot‑dog bun; typically dressed with butter/lemon or mayonnaise; often with celery/scallion. Sides: chips or fries.
6034357 (10.94): Nutrition entries listing calorie/macros for various lobster roll variants.
5837606 (10.82): On humanely killing lobster; context mentions New England Lobster Roll.
7157715 (10.60): Bread roll filled with chunks of lobster; common from New England to Canadian Maritimes.
6034350 (10.48): Classic New England lobster roll: hot dog bun with lobster salad in mayo.
2. 
A Lobster Roll is a bread …
> Ryan mcp repro

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Environment and Set-up:
- OS: Windows 11 (x64)
- Machine: ASUS VivoBook X1504VA
- CPU: 13th Gen Intel Core i7
- RAM: 16 GB
- Java: 21.0.8
- Python: 3.11.13
Issues and Results:
- Everything worked perfectly
- Initially I had trouble running trec_eval on Windows. Installed WSL and everything worked successfully without any errors.
This PR supersedes an earlier PR that I closed to provide a cleaner commit history.
> Add Pyserini onboarding reproduction log entries

- docs/conceptual-framework.md
- docs/conceptual-framework2.md
- docs/experiments-msmarco-passage.md
- docs/experiments-nfcorpus.md
Environment:
- OS: Windows 11 (x64), WSL
- Machine: Intel NUC11PHi7
- CPU: 11th Gen Intel Core i7
- RAM: 16 GB
Results:
- Everything worked
> Added to reproduction log

- pyserini/prebuilt_index_info.py
#2243 exposed a bunch of size errors that have crept in. We weren't actually checking before, so these errors when unnoticed.
> Fix errors in prebuilt index sizes

- pyserini/prebuilt_index_info.py
> Fix typos in prebuilt index texts
