pyserini/index/pyutils.py
pyserini/pyclass.py

Since DocVectorWeight enum is private in Anserini I couldn't port properly. This issue creates output files with wrong names(text.txt.docvector.(0-1).tar.gz). So it would be better to make DocVectorWeight public in IndexUtils.java. However, this piece of code works correctly.

Add/Refactoring IndexUtils #2

---

docs/Makefile
docs/make.bat
docs/source/conf.py
docs/source/index.rst
docs/source/modules.rst
docs/source/pyserini.collection.rst
docs/source/pyserini.index.rst
docs/source/pyserini.rst
docs/source/pyserini.search.rst

Created using Sphinx 2.3.0; primarily used for automatically-generated API documentation from docstrings. For a high-level user guide, the README.md appears adequate, at least for now.

Set up Sphinx documentation stubs

---

docs/source/conf.py
pyserini/index/pyutils.py
tests/test_indexutils.py

Closes #33 
Minor tweaks along the way; made Posting a top-level class, not hidden inside `IndexReaderUtils`.

Exposes methods for converting between internal Lucene docid and external collection docid

---

pyserini/collection/pycollection.py
pyserini/search/pysearch.py

We've made changes to Anserini head that are breaking changes to Pyserini. These break existing Pyserini unit tests.
After merging PR, we'll have the opposite problem: Pyserini unit tests will now fail on the official Maven Anserini 0.7.2 artifact.
There's no good way around this issue.

Fixed broken tests due to Anserini 0.7.3-SNAPSHOT

---

pyserini/index/pyutils.py
tests/test_indexutils.py

Fix for ‘ValueError: chr() arg not in range(0x110000)’ when calling a method from IndexReaderUtils (in pyutils) that contains a JString(term). For example after calling the get_document_vector(docid) method. This can be caused by a rare character in a term (See: https://github.com/kivy/pyjnius/issues/437). 
Specifying utf-8 encoding for the term solved this error: JString(term.encode(‘utf-8’)).

Fix for ValueError: chr() arg not in range

---

pyserini/analysis/pyanalysis.py
tests/test_analysis.py
tests/test_indexutils.py

`get_analyzer` returns the actual Lucene Analyzer, this PR adds an `Analyzer` Python class for performing actual analysis.
`get_analyzer` renamed `get_lucene_analyzer`, changed invocation.

Refactoring of analyzers

---

pyserini/analysis/pyanalysis.py
pyserini/index/pyutils.py
pyserini/pyclass.py
tests/test_analysis.py
tests/test_indexutils.py

- Implemented https://github.com/castorini/anserini/pull/1031 in Pyserini. 
- In order to get the term counts for stopwords, I added an option to the analyzer that allows to specify whether stopwords are filtered.

Optional analyser in get_term_counts and skip stopword option in analyzer.

---

pyserini/index/pyutils.py
pyserini/search/pysearch.py
tests/test_indexutils.py
tests/test_search.py

Better testing. Uploaded new version of CACM index with `contents` stored, and thus, testable.

Better alignment of API in SimpleSearcher and IndexReaderUtils for access docs

---

pyserini/search/pysearch.py
tests/test_loadtopics.py

Something like this works now!
```python
from pyserini.search import pysearch
topics = pysearch.get_topics('covid_round1')
print(f'{len(topics)} queries total')
for topic_id in sorted(topics.keys()):
print(topics[topic_id]['query'])
```

Exposes TREC COVID topics in Python

---

pyserini/pyclass.py
pyserini/search/pyquerybuilder.py
pyserini/search/pysearch.py
tests/test_indexutils.py
tests/test_querybuilding.py

Make it possible to construct queries in Pyserini

Query construction

---

pyserini/search/pysearch.py
tests/test_search.py

@Chriskamphuis @PepijnBoers I'd appreciate a sanity check on this... just _odd_.
On current HEAD, unit tests are broken: try with `python -m unittest`.
However, somewhat inexplicably, this patch fixes the bug...  and unit tests pass.
I don't really understand why... I suspect there's an underlying concurrency bug with how the `IndexReader` and `IndexSearcher` is being initialized on the Java end... any thoughts?

Fixed broken unit tests related to num_docs

---

pyserini/vectorizer.py

- After [PR 112](https://github.com/castorini/pyserini/pull/112), adopt `pyserini/vectorizer.py` to handle the scenario when term frequency `get_document_vector` return `None`.

Vectorizer handles term_freq is None

---

pyserini/index/pyutils.py
tests/test_indexutils.py

Pyserini end of https://github.com/castorini/anserini/pull/1218

Expose index statistics

---

pyserini/search/__main__.py

Anserini search has the tag `Anserini` and Pyserini's search is returning `anserini`. Notice the first character is capitalized in in Anserini but not Pyserini. Fixing this so that verify_simplesearch.py can work properly. This bug was introduced by me in a previous PR.

Fix pysearch tag mismatch

---

pyserini/search/__main__.py

[As @lintool suggested](https://github.com/castorini/pyserini/issues/137#issuecomment-634168692)
Here's a few examples of the resulting filename:
- core18-bm25+rm3-svm+lr-prcl.r_10-prcl.r_100-prcl.alpha_0.2.txt
- core18-bm25-svm-prcl.r_10-prcl.r_100-prcl.alpha_0.2.txt
- core18-bm25.txt
- core18-bm25+qld.txt

Better output_path naming on pyserini/search/__main__.py

---

pyserini/analysis/pyanalysis.py
pyserini/collection/pycollection.py
pyserini/index/pygenerator.py
pyserini/index/pyutils.py
pyserini/multithreading.py
pyserini/pyclass.py
pyserini/search/__main__.py
pyserini/search/pyquerybuilder.py
pyserini/search/pysearch.py
pyserini/search/reranker.py
pyserini/setup.py
scripts/classifier_prf/cross_validate.py
scripts/verify_simplesearcher.py
tests/test_analysis.py
tests/test_collection.py
tests/test_indexutils.py
tests/test_loadtopics.py
tests/test_nnsearch.py
tests/test_querybuilding.py
tests/test_search.py

Based on [pep8](https://pep8.org/#source-file-encoding), 
> Files using ASCII (in Python 2) or UTF-8 (in Python 3) should not have an encoding declaration.

Remove encoding info in boilerplate

---

pyserini/vectorizer.py
scripts/20newsgroups-replication.py

- Introduce new BM25Vectorizer
- Refactor Common logic of vectorizer to `Class VectorizerBase`
- Add test case in `20newsgroups-replication.py` with f1 score assertion
- Replace `MultinomialNB` with `LogisticRegression`, which renders better results
----------------------------
tfidf vectorizer with Linear Regression model score: 0.8359058
bm25 vectorizer with Linear Regression model score: 0.8421606
----------------------------
```
python scripts/20newsgroups-replication.py --vectorizer TfidfVectorizer
python scripts/20newsgroups-replication.py --vectorizer BM25Vectorizer
```

Introduce new BM25Vectorizer

---

README.md
pyserini/analysis/__init__.py
pyserini/analysis/_base.py
pyserini/collection/_base.py
pyserini/index/_base.py
pyserini/pyclass.py
pyserini/search/__init__.py
pyserini/search/_base.py
pyserini/search/_nearest_neighbor.py
pyserini/search/_searcher.py
pyserini/search/querybuilder.py
tests/test_analysis.py
tests/test_collection.py
tests/test_index_reader.py
tests/test_load_topics.py
tests/test_nnsearch.py
tests/test_querybuilder.py
tests/test_search.py

Previously, all the wrappers around Java classes were centralized in `pyclass`, which made imports a mess. Now, moved the wraps into separate subpackages, where they belong.

Refactoring and cleanup of pyclass

---

pyserini/search/__main__.py
scripts/verify_simplesearcher.py

`main` in `pyserini.search` change cmdline arg prefix from single to double dash. This patch makes verify_simplesearcher.py work again.

Fix command-line parameters in verify_simplesearcher.py

---

pyserini/vectorizer/__init__.py
pyserini/vectorizer/_base.py

- Refactor vectorizer.py into sub-module `vectorizer`
- Expose TfidfVectorizer and BM25Vectorizer in the sub-module

Refactor vectorizer.py into sub-module

---

pyserini/trectools/_base.py
tests/resources/simple_trec_run_filter.txt
tests/resources/simple_trec_run_keep_verify.txt
tests/resources/simple_trec_run_remove_verify.txt
tests/test_fusion.py
tests/test_trectools.py

- keep docs by qrels so that we get 100% judged
- remove docs by qrels so e.g. we don't want rnd1 docs when submitting round 2

TrecRun.remove/keep docs by qrels

---

integrations/test_trec_covid_stored_runs.py
integrations/test_verify_rrf.py
pyserini/util.py

+ Adds to `download_url` an option to check MD5 checksum.
+ Downloads and verifies checksum for round 3 and round 4 runs at: https://github.com/castorini/anserini/blob/master/docs/experiments-covid.md
+ Verifies fusion for round 3 and round 4 runs, such that they are identical to output of `trectools`.

Improve integration testing for TREC-COVID

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

OS: `Ubuntu 18.04.5 LTS`
Python: `Python 3.6.9`
```bash
(myenv) ubuntu:~/pyserini$ python tools/scripts/msmarco/msmarco_eval.py collections/msmarco-passage/qrels.dev.small.tsv runs/run.msmarco-passage.dev.small.tsv
MRR @10: 0.18741227770955546
(myenv) ubuntu:~/pyserini$ tools/eval/trec_eval.9.0.4/trec_eval -c -mrecall.1000 -mmap collections/msmarco-passage/qrels.dev.small.trec runs/run.msmarco-passage.dev.small.trec
map                   	all	0.1957
recall_1000           	all	0.8573
```
```bash
(myenv) ubuntu:~/pyserini$ tools/eval/trec_eval.9.0.4/trec_eval -c -mmap -mrecall.1000 tools/topics-and-qrels/qrels.msmarco-doc.dev.txt runs/run.msmarco-doc.dev.bm25.txt
map                   	all	0.2310
recall_1000           	all …
```

Add replication record for MS MARCO experiments

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

Results for both Doc and Passage retrieval are identical:
Passage:
```
❯ python3 tools/scripts/msmarco/msmarco_eval.py \
collections/msmarco-passage/qrels.dev.small.tsv runs/run.msmarco-passage.dev.small.tsv
MRR @10: 0.18741227770955546
❯ python3 tools/scripts/msmarco/convert_msmarco_to_trec_run.py \
--input runs/run.msmarco-passage.dev.small.tsv \
--output runs/run.msmarco-passage.dev.small.trec
Done!
❯ python3 tools/scripts/msmarco/convert_msmarco_to_trec_qrels.py \
--input collections/msmarco-passage/qrels.dev.small.tsv \
--output collections/msmarco-passage/qrels.dev.small.trec
Done!
❯ tools/eval/trec_eval.9.0.4/trec_eval -c -mrecall.1000 -mmap \
collections/msmarco-passage/qrels.dev.small.trec …
```

Pyserini Doc and Passage retrieval replication (Jerry Huang)

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

**OS:** Ubuntu 18.04.5 LTS
**Java:** jdk-11.0.9
**Maven:** Apache Maven 3.6.0
**Replication Results for MS MARCO Passage Retrieval:**
```
$ python3.9 tools/scripts/msmarco/msmarco_eval.py collections/msmarco-passage/qrels.dev.small.tsv runs/run.msmarco passage.dev.small.tsv
MRR @10: 0.18741227770955546
```
```
$ tools/eval/trec_eval.9.0.4/trec_eval -c -mrecall.1000 -mmap collections/msmarco-passage/qrels.dev.small.trec runs/run.msmarco-passage.dev.small.trec
map                   	all	0.1957
recall_1000           	all	0.8573
```
**Replication Results for MS MARCO Doc Retrieval:**
```
$ tools/eval/trec_eval.9.0.4/trec_eval -c -mmap -mrecall.1000 tools/topics-and-qrels/qrels.msmarco-doc.dev.txt runs/run.msmarco-doc.dev.bm25.txt …
```

MS MARCO Passage and Doc Retrieval Replication 

---

scripts/compute_doc_length_histogram.py

Sample invocation:
```
python scripts/compute_doc_length_histogram.py --index indexes/index-robust04-20191213/ \
--name 'Robust04' --output robust04 --plot robust04-doclengths.pdf
```
Output:
```
min: 6
max: 1027660
median: 348.0
mean: 548.5847849554002
```

Add script to compute length histograms

---

pyserini/util.py

As I turned out, I fixed one branch of the conditional but broke the other one. Both have been verified to work now.
The `index_directory` for the prebuilt branch is different!
Sorry for the noise.
cc @qguo96

Index download bugfix (take 2)

---

pyserini/util.py
scripts/check_download_links.py

We have a lot of documentation pages with download links. Instead of checking by hand to see if they still worked, I wrote a simple script to do it. Sample invocation:
```
python scripts/check_download_links.py --url https://raw.githubusercontent.com/castorini/anserini/master/docs/experiments-cord19.md
```

Simple script to verify Dropbox downloads

---

pyserini/search/__main__.py
pyserini/search/_searcher.py

Add support for output in MS MARCO in pyserini.search
Example:
```
python -m pyserini.search --topics msmarco_passage_dev_subset \
--index ms-marco-passage \
--output runs/run.msmarco-passage.dev.bm25.tsv \
--bm25 --msmarco
```
This is the head of output file:
```
2       1001873 1
2       1782337 2
2       4339075 3
2       4339068 4
2       7496507 5
2       7496506 6
2       6920058 7
2       6285817 8
2       4339072 9
2       7496505 10
```

Add support for output in MS MARCO in pyserini.search

---

README.md
docs/pypi-replication.md

We're able to directly replicate runs from the PyPI package!
As simple, as:
```bash
$ python -m pyserini.search --topics robust04 --index robust04 --output run.robust04.txt --bm25
```
Using pre-built indexes, stored topics, etc.

PyPI direct package replication instructions

---

README.md
docs/release-notes/release-notes-v0.10.0.1.md

The PyPI version had a broken link for downloading Robust04 index - didn't want to leave it broken.

Release notes for v0.10.0.1

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

Modifying replication log to track that I was successfully able to replicate the BM25 baseline for MSMARCO Passage and Document Ranking tasks.
My environment was Ubuntu 19.04 and am running Python 3.7.3.
No errors were encountered.

Replication of BM25 Baseline for MSMARCO Passage and Doc Ranking Tasks

---

docs/dense-retrieval.md
pyserini/dsearch/__main__.py

Minor tweaks to get replication working on my Mac.
Primarily for @MXueguang to CR, but need @rodrigonogueira4 or @ronakice for +1 once @MXueguang is happy.
HNSW, efficiency:
```
trial 1: 6980/6980 [05:16<00:00, 22.08it/s]
trial 2: 6980/6980 [05:02<00:00, 23.04it/s]
```
What Xueguang got:
```
MRR @10: 0.33395142584254184
```
What I got:
```
MRR @10: 0.33394187474416553
```
Small differences in scores.
Brute force, efficiency:
```
trial 1: 582/582 [28:28<00:00,  2.93s/it]
trial 2: 582/582 [27:20<00:00,  2.82s/it]
```
What Xueguang got:
```
MRR @10: 0.3344603629417369
```
What I got:
``` …
```

Updates to TCT-ColBERT dense retrieval replication

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

OS: Ubuntu 18.04.5 LTS
JDK: 11.0.9.1
Maven: 3.6.0
Successfully replicated results:

Replicated Pyserini: BM25 Baselines for MS MARCO Document + Passage Ranking

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

- Google Colab (Python3 Google Compute Engine Backend)
- Python 3.6
**Replicated results are exactly the same as the given results**
> Given Results
>My Results
>Given Results
>My Results

Replicated MS MARCO passage/document ranking results with Pyserini

---

docs/experiments-msmarco-passage.md

It seems that the file changes from `runs/msmarco-passage/qrels.dev.small.tsv` to `tools/topics-and-qrels/qrels.msmarco-passage.dev-subset.txt`. Therefore, the trec file name need to be changed to `tools/topics-and-qrels/qrels.msmarco-passage.dev-subset.trec` when running the `trec_eval` tool
In addition, the documentation seems to be missing the step running `convert_msmarco_to_trec_qrels.py`, which exists in the previous version.
I think the previous version of the documentation should be able to replicate the results. However, to accommodate the current naming of the files, I update the script accordingly and I am able to replicate the same result as mentioned in the documentation.

Fixing issues where Pyserini failed to produce metrices with TREC evaluation tool on MS MAROC passgae retrieval

---

README.md
docs/working-with-entity-linking.md
docs/working-with-spacy.md

- Break up spaCy and entity linking docs into two separate pages
- For spaCy, use the MS MARCO pre-built index (freely downloadable) with the Manhattan Project example (same as the entity linking page)
- Make https://github.com/castorini/pyserini#how-do-i-search-my-own-documents example consistent with spaCy example

Update spaCy and entity linking documents

---

integrations/test_simpledensesearcher_check_dpr.py
integrations/test_simpledensesearcher_check_msmarco.py

If we're running on our own internal servers, we can safely increase parallelism to make the tests run faster.
I'm still running tests to see how much speed increases... will report back once they finish.

Bump up parallelism on dense retrieval integration tests

---

integrations/test_tct_colbert_encoded.py
integrations/test_tct_colbert_otf.py

`test_tct_colbert_otf.py` is failing right now due to rounding difference - 0.3349 vs 0.3350 - on a Linux machine. This is a cleaner way to test.

Cleaner way to test TCT-ColBERT wrt OS differences

---

pyserini/index/_base.py

This PR changes the name WapoGenerator to WashingtonPostGenerator to be consistent with Anserini names.
Fix #406

Change WapoGenerator to WashingtonPostGenerator

---

README.md
docs/experiments-elastic.md
pyserini/search/_searcher.py

Minor tweaks as I was reproducing @jtibshirani 's PR.
For some reason, I got the following error:
```
File "/anaconda3/envs/python36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/anaconda3/envs/python36/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/Users/jimmylin/workspace/pyserini/pyserini/search/__main__.py", line 239, in <module>
hits = searcher.search(text, args.hits, query_generator=query_generator, fields=fields)
File "/Users/jimmylin/workspace/pyserini/pyserini/search/_searcher.py", line 116, in search
hits = self.object.searchFields(query_generator, JString(q), jfields, k)
File "jnius/jnius_export_class.pxi", line 256, in jnius.JavaClass.__init__
File …
```

Reproducing Elastic multi-field runs

---

pyserini/search/_searcher.py
pyserini/util.py

To solve issue [#414](https://github.com/castorini/pyserini/issues/414), I added cache_dir argument to the function from_prebuilt_index to specify the wanted cache directory. The same keyword has been used in huggingface transformers to specify the directory of cached models.

specifying cache directory to from_prebuilt_index function

---

integrations/test_simple_fusion_search_integration.py
integrations/test_trec_covid_stored_runs.py
integrations/test_verify_rrf.py
pyserini/prebuilt_index_info.py
pyserini/util.py

Apparently, Dropbox has a download bandwidth limit, which I tripped, causing a (temporary) ban. Moving away from Dropbox for "stable" links to avoid this in the future.
Added functionality to specify name of local filename when downloading.

Improvements to data downloading, moving away from Dropbox

---

tests/test_tokenization.py

Sanity checks our doc2query model.
With this, I want to revisit this issue: https://github.com/castorini/anserini/issues/1123 - let's try to make sure everything is in place, from the ground up.

Add tokenization tests

---

docs/experiments-ance.md
pyserini/dsearch/__main__.py
pyserini/encoded_query_info.py

re https://github.com/castorini/pyserini/issues/445 and https://github.com/castorini/pyserini/issues/396.
now all the experiments have both otf and encoded queries.
I'll update doc in a separate PR

update encoded query info

---

integrations/test_ance.py

Minor difference in effectiveness on macOS.

ANCE test fix on macOS

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

Ran both experiments on MacOS. All numbers obtained were exactly the same as in the provided README. 
- Downloads were quite slow using wget, so I had to manually download from the alternative mirror (dropbox), which was much easier. 
- I had to additionally install [sentence piece](https://github.com/google/sentencepiece#installation) which is not mentioned in the [README.md](https://github.com/castorini/pyserini/blob/master/README.md)

MS MARCO doc/passage replication

---

integrations/dense/test_tct_colbert.py

Otherwise, we get the following error:
```
======================================================================
FAIL: test_msmarco_passage_tct_colbert_bf_otf (test_tct_colbert.TestSearchIntegration)
----------------------------------------------------------------------
File "/store/scratch/jimmylin/pyserini/integrations/dense/test_tct_colbert.py", line 54, in test_msmarco_passage_tct_colbert_bf_otf
self.assertAlmostEqual(score, 0.3350, delta=0.0001)
AssertionError: 0.3349 != 0.335 within 0.0001 delta
----------------------------------------------------------------------
```
This is running on `orca`.

Increased tolerance for dense test case

---

pyserini/tokenize_json_collection.py
tests/test_load_qrels.py

https://github.com/castorini/pyserini/issues/534 and https://github.com/castorini/pyserini/issues/518

Fix unittests tests

---

docs/experiments-kilt.md
scripts/kilt/anserini_retriever.py

OS: Ubuntu 21.04 
Replication results:
> + python KILT/kilt/eval_retrieval.py pyserini/runs/kilt_document/fever-dev-kilt.jsonl KILT/data/fever-dev-kilt.jsonl --ks 1,100,1000
> OrderedDict([   ('Rprec', 0.3821230234721237),
>                 ('precision@1', 0.36202604366143243),
>                 ('precision@100', 0.009222520107239729),
>                 ('recall@100', 0.8840571103329627),
>                 ('success_rate@100', 0.8933358866334737),
>                 ('precision@1000', 0.0010051704327843417),
>                 ('recall@1000', 0.9564598493552918),
>                 ('success_rate@1000', 0.962562236690923)])
> + python KILT/kilt/eval_retrieval.py pyserini/runs/kilt_document/aidayago2-dev-kilt.jsonl KILT/data/aidayago2-dev-kilt.jsonl --ks 1,100,1000
> OrderedDict([   ('Rprec', …

Kilt Reproduction

---

docs/experiments-ance.md
docs/experiments-tct_colbert.md

Notes: Used Pyserini (0.12.0) via Pip. Only examined passages; CPU running over pre-built indexes; reproduced both brute force and HNSW runs.
Package version info:
```
faiss-cpu==1.7.0
torch==1.7.1
transformers==4.0.0
```

Update TCT ColBERT repro log

---

pyserini/demo/msmarco.py

Solves https://github.com/castorini/pyserini/issues/548 (interactive retrieval demo). 
This PR adds support for `dense` and `hybrid` retrievers to the interactive demo through the `/mode` command. 
For these retrievers, this PR adds support for 2 encoder models, `tct` and `ance`.
Also, with `tct`, there are 2 possible indices: (1) HNSW index i.e. and (2) brute-force index i.e. msmarco-passage-tct_colbert-bf. I used (1) in this PR.

Add retrievers and models to demo

---

tests/test_tokenization.py

Added mBERT and XLM-R tokenizer test cases for the following African languages:
1. Amharic
2. Afaan Oromooo
3. Hausa
4. Igbo
5. Nigerian Pidgin
6. Somali
7. Swahili
8. Tigrinya
9. Yoruba
Fixes #578 @

Tokenizer test cases for 9 African Languages

---

docs/experiments-distilbert_tasb.md

The reproduction basically follow distill bert KD. Currently, the score is a bit lower than the numbers reported in the hub (MRR@10 .344 vs .347) even when I use fp16 mixed precision. I guess the results are acceptable and we can wait until Sebastian has time to release his code to make a comparison? I've already had the pre-computed index and query embeddings in Tuna. Shall I upload to dropbox ?

add tasb msmarco dev subset reproduce

---

pyserini/dindex/__main__.py
pyserini/dindex/_base.py

the `title-delimiter` only works for DprEncoder for now, since wiki passages have titles.
the input collection has '\n' to split title and passage
```
{"id": "doc1", "contents": "title1\ncontents of doc one."}
```
the MSMARCO passages don't have titles, so we don't need add  `title-delimiter` for ANCE encoder (we manually handle this for now).
input can just be:
```
{"id": "doc1", "contents": "contents of doc one."}
```

Fix dindex bug

---

pyserini/demo/dpr.py

This PR adds a demo for DPR, similar to [MSMarcoDemo](https://github.com/castorini/pyserini/blob/master/pyserini/demo/msmarco.py). Currently, it only supports `DPR-Multi` and `/random` chooses topics from  [`Natural Questions`](https://github.com/castorini/pyserini/blob/master/pyserini/search/_base.py#L198) and [`Trivia`](https://github.com/castorini/pyserini/blob/master/pyserini/search/_base.py#L202) collections.
Resolves #633

Add DPR demo

---

pyserini/output_writer.py
pyserini/vsearch/__init__.py
pyserini/vsearch/__main__.py
pyserini/vsearch/_vsearcher.py
pyserini/vsearch/index.py
scripts/deepimpact/brute-force.py

current process to replicate numbers in ICTIR paper:
1. download bm25 hnsw index
```
wget https://www.dropbox.com/s/3i5vjhy4snj0yd8/bm25_hnsw_40_2500.tar.gz
tar -xvf /bm25_hnsw_40_2500.tar.gz
```
2. download msmarco-passage-dev-subset bm25 vectors:
```
wget https://www.dropbox.com/s/gkgeocv2ktfapl6/msmarco-passage-dev-subset-bm25-vectors.json
```
3. run vsearch
```
python -m pyserini.vsearch --index sparse_bm25_indexes/40_2500/ --topics msmarco-passage-dev-subset-bm25-vectors.json --output bm25_ann.run --is-sparse --dim 202514 --batch-size 36 --threads 12
```
Notes:
- we will need a module `/pyserini/vindex` to generate (1)
- (2) currently has following format
```
[
{
"id": 1102330,
"topic": "why do people grind teeth in sleep",
"vector": [
[71919,  92561, 144918, 169850, 179980, 196713], …
```

vsearch based on hnsw (nmslib)

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

```
- MS MARCO Passage Ranking: 2020 Macbook Pro, macOS Big Sur, 8GB RAM, 500 GB HD
- MS MARCO Document Ranking: GCP e2-standard-4, Ubuntu 18.04 LTS, 4 vCPU (8GB RAM), 1500 GB SSD
```
Tried running document ranking on 2020 Macbook Pro, but it runs out of memory at indexing. In `top`, Python seems to run out of memory at ~2 GB / ~500k documents indexed. Curious, since I was able to reproduce MS MARCO document ranking locally in Anserini.

Reproduced BM25 baselines for MS MARCO Passage and Document Ranking

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

Get exactly same result as provided. Screenshots are post
Environment:
OS: macOS Big Sur 11.4
Python: 3.9.5
Java: openjdk 11.0.5 2019-10-15
Issue encountered:
mvn doesn't set ANSERINI_CLASSPATH properly when compile code
Solved: Manually adding `export ANSERINI_CLASSPATH='/Users/zizeng/Code/anserini/target'` (Change `zizeng` to your username) to `.bash_profile`(or `.zshrc` depends on our shell)

Reproduce pyserini: BM25 Baselines for MS MARCO Passage/Document Ranking Experiment 

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

Environment:
OS: macOS 11.2.1 (Big Sur)
Java: 11.0.9.1 (openjdk)
Python: 3.9.1
Problems encountered:
- Initially did not have the required libraries, resolved with https://github.com/castorini/pyserini/blob/master/docs/installation.md

Replicated msmarco-doc and msmarco-passage experiments for initial screening, Matthew Yang

---

docs/experiments-ltr-msmarco-passage-training.md

```
recall@10:0.48367956064947465
recall@20:0.5796442215854822
recall@50:0.683966093600764
recall@100:0.7545964660936009
recall@200:0.8033428844317098
recall@500:0.8454512893982808
recall@1000:0.8573424068767909
```
Evaluating the results using:
1) MS MARCO evaluation script
```
python tools/scripts/msmarco/msmarco_passage_eval.py \
tools/topics-and-qrels/qrels.msmarco-passage.dev-subset.txt runs/run.ltr.msmarco-passage.tsv
MRR @10: 0.24831019466048032
```
2) ` trec_eval`
```
tools/eval/trec_eval.9.0.4/trec_eval -c -mrecall.1000 -mmap \
collections/msmarco-passage/qrels.dev.small.trec runs/run.ltr.msmarco-passage.trec
map                   	all	0.2564
recall_1000           	all	0.8573 
```

Reproduction of ltr-msmarco-passage-training results

---

docs/experiments-msmarco-v2-unicoil.md

Confirmed uniCOIL by itself as well as hybrids:
+ Passage: Dense-sparse hybrid retrieval (uniCOIL zero-shot + TCT_ColBERT_v2 zero-shot)
+ Passage: Dense-sparse hybrid retrieval (uniCOIL zero-shot + TCT_ColBERT_v2 trained)
+ Doc: Dense-sparse hybrid retrieval (uniCOIL zero-shot + TCT_ColBERT_v2 zero-shot)
+ Doc: Dense-sparse hybrid retrieval (uniCOIL zero-shot + TCT_ColBERT_v2 trained)
Results for zero shot matched exactly.
Results for trained versions differed a tiny bit (four places after the decimal point).

Add to uniCOIL repro log

---

docs/experiments-msmarco-v2-tct_colbert-v2.md

Issue #738
Results:
1. passage v2 (zero-shot)
```
$ python -m pyserini.eval.trec_eval -c -M 100 -m map -m recip_rank collections/passv2_dev_qrels.tsv runs/run.msmarco-passage-v2-augmented.tct_colbert-v2-hnp.0shot.dev1.trec
map                     all     0.1461
recip_rank              all     0.1473
$ python -m pyserini.eval.trec_eval -c -m recall.100,1000 collections/passv2_dev_qrels.tsv runs/run.msmarco-passage-v2-augmented.tct_colbert-v2-hnp.0shot.dev1.trec
recall_100              all     0.5873
recall_1000             all     0.8321
```
2. passage v2 (fine-tuned)
```
$ python -m pyserini.eval.trec_eval -c -M 100 -m map -m recip_rank collections/passv2_dev_qrels.tsv runs/run.msmarco-passage-v2-augmented.tct_colbert-v2-hnp.psg_v2_ft.dev1.trec
map                     all     0.1981 …
```

reproduce TCT-ColBERTv2 for MS MARCO (V2)

---

README.md
docs/experiments-unicoil-tilde-expansion.md

Hi, 
I have added the instructions to reproduce results for uniCOIL with TILDE expansion on MS MARCO passage v1.
The anserini comparable guide has not been added yet. Will do it as soon as possible, same for MS MARCO v2 guide.
And feel free to change corpus or index downloading links if they do not make sense to you.

add uniCOIL TILDE expansion instructions for MS MARCO passage v1

---

README.md
docs/experiments-msmarco-v2-unicoil-tilde-expansion.md

Hi, I have add the instructions to reproduce the results we get with uniCOIL TILDE expansion on MS MARCO V2 passage ranking. The index and corpus download links are directly copied/modified from the uniCOIL MS MARCO V1 passage ranking docs, please feel free to change them if needed. These two files are currently uploading to my Google Drive, I will send the link once upload finishes.

add uniCOIL TILDE expansion reproduce instructions for MS MARCO V2 passage ranking

---

docs/experiments-unicoil.md
pyserini/query_iterator.py
pyserini/search/_base.py

+ Add ability to read compressed topics.
+ Add documentation for on-the-fly query encoding.
For on-the-fly query encoding, I get on my iMac Pro:
```
MRR @10: 0.35088535270841803
```
And on `orca`:
```
MRR @10: 0.3508734138354477
```
Both scores are a tiny bit lower, but still reasonably close pre-computed queries, which we get:
```
MRR @10: 0.35155222404147896
```

Update uniCOIL + d2q passage

---

docs/experiments-unicoil.md

+ I rewrote the documentation to be more consistent - otf and then precomputed queries
+ both passage and doc now have otf and precomputed results.

Reorganize uniCOIL + doc2query reproduction documentation

---

docs/experiments-msmarco-v2-unicoil-tilde-expansion.md

get exactly same number.
On Ubuntu 20.04 machine

add msmarco v2 tilde reproduce log

---

README.md
docs/experiments-adore.md
docs/experiments-vector-prf.md

Hi, I have added the adore reproducing instruction as mentioned in #783 
However, the 'on-the-fly' query encoder feature is not working for ADORE at the moment due to the original checkpoint is trained on an old version of transformers (`transformers==2.8.0`). The otf reproducing results cannot match what was reported in the paper.

Add adore reproduce experiments

---

pyserini/search/_impact_searcher.py

queries tokens probably not in idf list

fix bug in impact searcher 

---

pyserini/analysis/_base.py
pyserini/index/_base.py
pyserini/search/_impact_searcher.py
pyserini/search/_searcher.py
requirements.txt
tests/test_index_reader.py

When using pyjnius in a version prior 1.3.0, creating a JString with non-ASCII characters resulted in a failure. To work around this issue, the strings where manually encoded to utf8 (`.encode('utf-8')`), however, this is not necessary anymore with newer pyjnius versions.
The manual `.encode('utf-8')` caused problems under Windows when the environment variable `_JAVA_OPTIONS=-Dfile.encoding=UTF-8` was not set.
See the full discussion here: https://github.com/castorini/pyserini/issues/770
Remove `.encode('utf-8')` everywhere in the code and bump pyjnius version to `>=1.3.0`. With this fix, it is not required to use an extra environment variable under Windows anymore.
Added a test that ensures that a newer, fixed version of pyjnius is being used.

Remove unnecessary utf8 encoding causing problems under Windows

---

README.md
docs/experiments-dpr-compression.md
docs/experiments-msmarco-v2.md
pyserini/index/__main__.py
pyserini/search/_base.py
tests/test_load_topics_qrels.py

+ Closes #745, #715.
+ Added bindings to JQrels.TREC2020_BL
+ For Lucene indexing supports single and double hyphens (e.g., `--collection` and `-collection`)

Update MS MARCO V2 reproduction documentation (include variants)

---

docs/experiments-unicoil-tilde-expansion.md
pyserini/search/_base.py
tests/test_load_topics_qrels.py

Pyserini counterpart for this: https://github.com/castorini/anserini/pull/1670
Expose queries stored in Anserini jar in Python.

Add bindings for pre-tokenized queries for sparse learned models

---

docs/usage-pyjnius.md
pyserini/analysis/_base.py
pyserini/index/_base.py
pyserini/ltr/_base.py
pyserini/search/_impact_searcher.py
pyserini/search/_nearest_neighbor.py
pyserini/search/_searcher.py
tests/test_analysis.py
tests/test_index_reader.py

As discussed in https://github.com/castorini/pyserini/issues/770, converting Python strings to Java strings using `JString(...)` does not work correctly if the string contains an emoji. However, letting the `pyjnius` library perform the conversion automatically without the explicit `JString` conversion seems to work correctly.
Unit tests pass successfully. @lintool, you can check the regression tests on your side to make sure it doesn't break anything.

Drop JString wrapping

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

Successfully reproduced results
Ubuntu 20.04.03 LTS
openjdk version "11.0.9.1-internal"
Python 3.6.13
Maven 3.6.3

Reproduced MSMARCO passage and document ranking experiment

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

I have done the reproduction. There was one problem that I ran into (I was working on an OSX Big Sur Mac laptop):
and this eventually led to the following error when performing retrieval:
One way of eliminating the errors is to change `conda create -n pyserini python=3.6` into `conda create -n pyserini python=3.8`. Note that `python=3.9` here didn't work for me because I remember one faiss-related module saying that it needed below 3.9.

Append to MS MARCO reproduction logs

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

Reproduced results from MS MARCO passage and doc ranking exercises as part of initial screening exercise
Was able to reproduce the expected values, below the issues I encountered (Same issues as when I was doing the anserini reproduction exercise):
- Since I was working on a Windows machine, there were small differences in the commands such as using backslashes for file paths, and gzip rather than gunzip for decompression.
Environment Setup:
Windows 10 Pro Version 20H2
Java: openjdk 11.0.9.1
Python: 3.8.4

Reproduction of MS MARCO Passage and Doc Ranking

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

- Reproduced pyserini passage ranking and document ranking experiments for the [screening exercise](https://github.com/lintool/guide/blob/master/ura.md)
Environment:
```bash
$ java --version
openjdk 11.0.9.1 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)
$ mvn --version
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /opt/homebrew/Cellar/maven/3.8.4/libexec
Java version: 11.0.9.1, vendor: Azul Systems, Inc., runtime: /Users/kevinwang/opt/anaconda3/envs/pyserini
Default locale: en_CA, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```
Issues encountered:
When running the unit tests, I get the following error …

Reproduce passage ranking and document ranking experiments

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

Replicated and achieved expected results, as outlined in the experiment docs.
Environment:
Ubuntu 18.04.5 LTS
Java: `openjdk 11.0.13 2021-10-19`
Python: version 3.6.9
Notes:
* Due to being on ubuntu, I used `python3` instead of `python` when running pythons scripts
* Pytorch was installed normally using `pip install torch`
* Faiss was installed using `pip install faiss-cpu --no-cache` (installing via `pip install faiss` resulted in an ImportError)
The above configuration worked with the unit tests (`python3 -m unittest`)

Reproduce experiment results for MS-MARCO passage and document ranking

---

integrations/clprf/test_trec_covid_r3.py

URL location no longer exists due to @rodrigonogueira4 's reorg of his Google storage data. Changing to NIST URL.

Fix test case URL in integrations/clprf/test_trec_covid_r3.py

---

pyserini/trectools/_base.py

* The rank function is changed in pandas 1.3.5 from 1.1.4 which caused the Value Error in the fusion part of clprf regression tests. Fixed it by only ranking one column one now.

Fix the Core17 clprf Regression Test Failure 

---

integrations/sparse/test_simple_fusion_search_integration.py

Fixed brittle unit test: integrations.sparse.test_simple_fusion_search_integration.TestSearchIntegration

---

docs/experiments-dpr.md
docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md
pyserini/demo/dpr.py
pyserini/demo/msmarco.py

Platform used: Orca
Confirmed that I was able to reproduce all results, with one small difference:
For NQ with DPR-Single, using DPR retrieval with brute-force index, the top 100 accuracy result I recorded was 0.8609 rather than 0.8610.
Also fixed a small typo I saw when playing around with the Pyserini dense/sparse retrieval demos

DPR Results Reproduction

---

docs/experiments-dpr.md

Reproduced DPR results on orca
- Ran into same issue as @vivianliu0: "For NQ with DPR-Single, using DPR retrieval with brute-force index, the top 100 accuracy result I recorded was 0.8609 rather than 0.8610.". I got Top100 accuracy of 0.8609418282548477 to be exact instead of 0.8610.

Reproduced DPR results

---

docs/prebuilt-indexes.md
pyserini/prebuilt_index_info.py

Added CS Vault mirrors for new versions.

Deprecate old versions of MS MARCO (V1) pre-built indexes

---

docs/experiments-msmarco-v2-unicoil-tilde-expansion.md
docs/experiments-spladev2.md

I've re-run the following experiments (picked randomly). I've updated the documentation as well to cater for the new way of how to invoke search and index functions. I ran the following experiments :  
- Pyserini: SPLADEv2 for MS MARCO V1 Passage Ranking
- Pyserini: uniCOIL (w/ TILDE) for MS MARCO (V2) Passage Ranking
- Python 3.8.4 (with a pip install pyserini) 
-  Intel Xeon CPU 2.20Ghz 
- 16GB of RAM
- NVIDIA T4 GPU (CUDA version 11.4 - 495.53 driver version) 
- Debian 10 (4.19.0.18-cloud) 
There is a slight difference in the score I've obtained for Spladev2. This is within the reported value
```
MRR @10: 0.3681425125294513
```
Let me know if you do require any further information and I'm happy to provide

SPLADEv2 and uniCOIL reproduction experiment

---

docs/prebuilt-indexes.md
pyserini/encode/__main__.py
pyserini/encode/_base.py
pyserini/encode/merge_faiss_index.py
pyserini/prebuilt_index_info.py
pyserini/resources/index-metadata/faiss.mrtydi-v1.1-arabic.20220207.5df364.README.md
pyserini/resources/index-metadata/faiss.mrtydi-v1.1-bengali.20220207.5df364.README.md
pyserini/resources/index-metadata/faiss.mrtydi-v1.1-english.20220207.5df364.README.md
pyserini/resources/index-metadata/faiss.mrtydi-v1.1-finnish.20220207.5df364.README.md
pyserini/resources/index-metadata/faiss.mrtydi-v1.1-indonesian.20220207.5df364.README.md
pyserini/resources/index-metadata/faiss.mrtydi-v1.1-japanese.20220207.5df364.README.md
pyserini/resources/index-metadata/faiss.mrtydi-v1.1-korean.20220207.5df364.README.md
pyserini/resources/index-metadata/faiss.mrtydi-v1.1-russian.20220207.5df364.README.md
pyserini/resources/index-metadata/faiss.mrtydi-v1.1-swahili.20220207.5df364.README.md
pyserini/resources/index-metadata/faiss.mrtydi-v1.1-telugu.20220207.5df364.README.md
pyserini/resources/index-metadata/faiss.mrtydi-v1.1-thai.20220207.5df364.README.md
pyserini/util.py
tests/test_encoder.py

1. the mdpr index on mrtydi v1.1 and corresponding readme; 
2. the script (to merge the faiss indexes generated per shard;
- merge_faiss_index.py
3. add a `--delimiter` argument for the `encode` module, use to parse the fields under `doc['contents']`
- pyserini/encode/_\_main__.py
- pyserini/encode/_base.py
4. allow the directory extracted from tarball different from the specified index name, as long as there is only one directory under it. This is for the case when ppl didn't name the file correctly before compressing it into tarball and upload to server, which is costly to redo. **probably need more review attention**
- pyserini/util.py

Mrtydi mdpr index

---

docs/experiments-msmarco-v2-unicoil.md
docs/experiments-unicoil.md
pyserini/search/lucene/_base.py

Update docs. Confirmed the following:
MS MARCO V2 passage:
```
python -m pyserini.search.lucene \
--topics msmarco-v2-passage-dev-unicoil-noexp \
--index indexes/lucene-index.msmarco-v2-passage-unicoil-noexp-0shot/ \
--output runs/run.msmarco-v2-passage-unicoil-noexp-0shot.dev.txt \
--batch 144 --threads 36 \
--hits 1000 \
--impact
$ python -m pyserini.eval.trec_eval -c -M 100 -m map -m recip_rank msmarco-v2-passage-dev \
runs/run.msmarco-v2-passage-unicoil-noexp-0shot.dev.txt
Results:
map                   	all	0.1333
recip_rank            	all	0.1342
$ python -m pyserini.eval.trec_eval -c -m recall.100,1000 msmarco-v2-passage-dev \
runs/run.msmarco-v2-passage-unicoil-noexp-0shot.dev.txt
Results:
recall_100            	all	0.4976
recall_1000           	all	0.7010
---
python -m …
```

Add uniCOIL pre-encoded query bindings for MS MARCO V2 (doc, passage) + V1 doc

---

scripts/mrtydi/combine_corpus.py
scripts/mrtydi/index-combined-corpus.sh
scripts/mrtydi/mbert-tokenize-mrtydi.py
scripts/mrtydi/search.py

The script to prepare the mbert tokenized Mrtydi, and the script to index and search in it.
`scripts/mrtydi/mbert-tokenize-mrtydi.py` is just for reference, `window-combined-corpus.sh` would download the prepared corpus and index on it. and `search.py` help to play around in the built index

Mrtydi mbert prep and index

---

pyserini/prebuilt_index_info.py

+ change 'text' pointer field of Faiss indexes to point to new pre-built indexes.
+ change single to double quotes. 
(Rationale is that these are supposed to be JSON entities, and JSON does not allow single quotes.)

Refactor pre-built index metadata

---

pyserini/search/lucene/__init__.py
pyserini/search/lucene/_geo_searcher.py

Changes:
- `_geo_searcher.py`: added wrapper class for `SimpleGeoSearcher`
- `__init__.py`: added newly implemented class to imports
Ran a simple test in the script part of this [file](https://github.com/d1shs0ap/giraffe/blob/main/server/app.py).
Should I add the generated HydroRIVERS index to `anserini-data` and add support for downloading prebuilt indexes? Or perhaps we can do this later down the road... Let me know what you think.

Geosearch wrapper

---

docs/experiments-bpr.md
docs/experiments-ltr-msmarco-passage-reranking.md
docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md
docs/experiments-msmarco-v2.md
docs/experiments-trec2021-clinical-trials.md
docs/experiments-tripclick-doc.md
docs/installation.md

I spent some time trying out the reproductions, making some fixes to the documentation where I saw necessary. 
I was able to do the following experiments: [BM25 baseline for MS MARCO V1 Passage Ranking](https://github.com/castorini/pyserini/blob/master/docs/experiments-msmarco-passage.md), [BM25 baseline for MS MARCO V1 Document Ranking](https://github.com/castorini/pyserini/blob/master/docs/experiments-msmarco-doc.md), [BPR experiments](https://github.com/castorini/pyserini/blob/master/docs/experiments-bpr.md).
I also attempted the LTR Filtering experiments: [MS MARCO V1 Passage](https://github.com/castorini/pyserini/blob/master/docs/experiments-ltr-msmarco-passage-reranking.md) and [MS MARCO V1 Document](https://github.com/castorini/pyserini/blob/master/docs/experiments-ltr-msmarco-docum …

Logged Reproductions and Improved Docs

---

docs/prebuilt-indexes.md
pyserini/prebuilt_index_info.py
pyserini/resources/index-metadata/lucene-index.msmarco-v1-doc-segmented-unicoil-noexp.20220322.2f4058.README.md
pyserini/resources/index-metadata/lucene-index.msmarco-v1-passage-unicoil-noexp.20220322.2f4058.README.md

These commands now work:
```
python -m pyserini.search.lucene \
--index msmarco-v1-passage-unicoil-noexp \
--topics msmarco-passage-dev-subset-unicoil-noexp \
--output runs/run.msmarco-passage.unicoil-noexp.tsv \
--output-format trec \
--batch 36 --threads 12 \
--hits 1000 \
--impact
python -m pyserini.eval.trec_eval -c -m map msmarco-passage-dev-subset runs/run.msmarco-passage.unicoil-noexp.tsv
python -m pyserini.eval.trec_eval -c -M 10 -m recip_rank msmarco-passage-dev-subset runs/run.msmarco-passage.unicoil-noexp.tsv
python -m pyserini.eval.trec_eval -c -m recall.100 msmarco-passage-dev-subset runs/run.msmarco-passage.unicoil-noexp.tsv
python -m pyserini.eval.trec_eval -c -m recall.1000 msmarco-passage-dev-subset runs/run.msmarco-passage.unicoil-noexp.tsv
python -m …
```

Install pre-built indexes for MS MARCO v1 (doc + passage), uniCOIL noexp

---

pyserini/eval/evaluate_dpr_retrieval.py

Fixes issue #1067 
I was not able to test this fix. I tried to download the index needed to get `runs/run.dpr.nq-test.single.bf.bm25.trec` and its DPR format before running the command:
> python -m pyserini.eval.evaluate_dpr_retrieval \
--retrieval runs/run.dpr.nq-test.single.bf.bm25.json \
--topk 20 100
However, the index was quite large (55GB). I believe the fix should work though as it's not a big change.
Are there much smaller indexes available that make it easier to test out functionalities and fixes quickly?

Reduced DPR acccuracy's figures of precision

---

pyserini/search/lucene/_searcher.py
tests/test_search.py

Fixes #695 
Raises an error when an attempt is made at setting RM3 for indexes without document vectors.

Improved error message for RM3 expansion doc vector issue

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

Reproduced the pyserini passage and document ranking experiments for the [initial screening exercise](https://github.com/lintool/guide/blob/master/ura.md).
Environment:
```
$ java --version
openjdk 11.0.9.1 2020-11-04 LTS
OpenJDK Runtime Environment Zulu11.43+55-CA (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+55-CA (build 11.0.9.1+1-LTS, mixed mode)
$ mvn --version
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /Users/jxian/opt/anaconda3/envs/pyserini-dev/opt/maven
Java version: 11.0.9.1, vendor: Azul Systems, Inc., runtime: /Users/jxian/opt/anaconda3/envs/pyserini-dev
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```
Issues Encountered:
When running the unit tests, I get the …

Update replication log for MS-MARCO passage and document ranking experiments

---

docs/experiments-ltr-msmarco-passage-reranking.md

minor tweaks, e.g., use internal pyserini scripts for eval.

Add to repro log for MS MARCO passage LTR

---

integrations/sparse/test_nmslib.py

Test fails on my iMac Pro because the score tolerance is too tight:
```
======================================================================
FAIL: test_msmarco_passage_deepimpact_nmslib_hnsw (integrations.sparse.test_nmslib.TestSearchIntegration)
----------------------------------------------------------------------
File "/Users/jimmylin/workspace/pyserini/integrations/sparse/test_nmslib.py", line 59, in test_msmarco_passage_deepimpact_nmslib_hnsw
self.assertAlmostEqual(score, 0.2979, delta=0.0001)
AssertionError: 0.2977 != 0.2979 within 0.0001 delta (0.00019999999999997797 difference)
----------------------------------------------------------------------
```

Increase tolerance in nmslib test for matching scores

---

docs/experiments-vector-prf.md
pyserini/search/faiss/__main__.py
pyserini/search/faiss/_prf.py

Hi @lintool , I implemented the negative prf passage for vector Rocchio prf and did a bit of refactoring.
I tested this with `distilbert-dot-tas_b`, here is what I got:
This is the previous Rocchio run which uses the top 5 passages as positive prf signals and no negative passages:
```
python -m pyserini.search.faiss --topics dl19-passage \
--index msmarco-passage-distilbert-dot-tas_b-b256-bf \
--encoder sebastian-hofstaetter/distilbert-dot-tas_b-b256-msmarco \
--batch-size 64 \
--threads 12 \
--output runs/run.dl2019.distilbert-dot-tas_b.rocchio_a0.4_b0.6_g0.6_topk5_bottomk0.trec \
--prf-method rocchio \
--prf-depth 5 \
--rocchio-alpha 0.4 \
--rocchio-beta 0.6 \
--rocchio-topk 5 \
```
This is using the top 5 passages as positive and the bottom 5 passages as negative prf signals:
``` …
```

refactor vector prf and add negative prf passages for rocchio

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md
pyserini/encode/_base.py

Reproduced the MS MARCO passage and document ranking experiments results as part of [initial screening](https://github.com/lintool/guide/blob/master/ura.md#initial-screening).
- Java version 11.0.15
- Maven version 3.8.5
- Python version 3.8.13 with Conda version 4.11.0
- MacOS Monterey version 12.3.1 (21E258)
When running the unit tests with `python -m unittest` for the first time, the following tests failed:
- `test_tct_colbert_v2_encoder_cmd`
- `test_tct_colbert_v2_encoder_cmd_shard`
- `test_faiss_hnsw`
- `test_faiss_pq`
This was due to the cache directories not being properly created, particularly `~/.cache/pyserini/temp_index` and `~/.cache/pyserini/temp_index-0`. The tests use `os.mkdir` to create the directories, which succeeds only when all the intermediate directories exist. In …

Reproduce MS MARCO passage and document ranking experiments results and fix unit tests failure

---

integrations/utils.py

Ignore the first few lines of output until we get to 'Results'; then start parsing.

Fix bug: parsing results of trec_eval

---

docs/experiments-gar-t5.md

There were some differences in the top 300 scores. The other scores matched perfectly. I have updated the doc accordingly.

Add to repro log for GAR-T5 experiments

---

pyserini/query_iterator.py

BEIR datasets may contain string type topic ids. This throws an error with ``TsvIntTopicReader``.  
By default to work on this, we change our topic reader to ``TsvStringTopicReader`` for BEIR dataset evaluation.
Kind Regards,
Nandan Thakur

Change topic reader from TsvIntTopicReader to TsvStringTopicReader for beir datasets

---

docs/experiments-dkrr.md
docs/experiments-gar-t5.md

- runs were previously incorrectly named with gar-bart instead of gar-t5
- replaced $ANSERINI/src/main/python/fusion.py with python -m pyserini.fusion
- Added hybrid retrieval results with DKRR to tables

Refactor gar-t5 experiments doc

---

docs/prebuilt-indexes.md
pyserini/prebuilt_index_info.py
pyserini/resources/index-metadata/lucene-index.msmarco-v1-doc-d2q-t5-docvectors.20220525.30c997.README.md
pyserini/resources/index-metadata/lucene-index.msmarco-v1-doc-segmented-d2q-t5-docvectors.20220525.30c997.README.md
pyserini/resources/index-metadata/lucene-index.msmarco-v1-passage-d2q-t5-docvectors.20220525.30c997.README.md
pyserini/resources/index-metadata/lucene-index.msmarco-v2-doc-d2q-t5-docvectors.20220525.30c997.README.md
pyserini/resources/index-metadata/lucene-index.msmarco-v2-doc-segmented-d2q-t5-docvectors.20220525.30c997.README.md
pyserini/resources/index-metadata/lucene-index.msmarco-v2-passage-augmented-d2q-t5-docvectors.20220525.30c997.README.md
pyserini/resources/index-metadata/lucene-index.msmarco-v2-passage-d2q-t5-docvectors.20220525.30c997.README.md

This is the missing row in our repro matrix for our SIGIR 2022 paper.

Installing Pre-built Indexes for MS MARCO V1/V2 doc2query-T5 w/ RM3 

---

integrations/sparse/test_trec_eval_compute_judged.py
integrations/sparse/test_verify_rrf.py
pyserini/eval/trec_eval.py
tests/resources/simple_trec_run_unjudged_keep.txt
tests/resources/simple_trec_run_unjudged_remove.txt
tests/test_trectools.py

Previously, computing J@K is via the option `-cutoffs.x,y,z`;
I've refactored so that it's just like yet another metric, e.g., `-m judged.10,100,1000`
Also, added a test case, based on ground truth here:
https://github.com/castorini/anserini/blob/master/docs/experiments-covid.md
Running regression tests right now to make sure nothing is broken.

Refactor computation of judged@k in trec_eval

---

pyserini/search/lucene/_geo_searcher.py

Updates:
Added import to `JLongPoint` to resolve the following error in WaterSHEDS:

Fixed import JLongPoint error

---

pyserini/eval/trec_eval.py
tests/resources/simple_trec_run_unjudged_keep.txt
tests/resources/simple_trec_run_unjudged_remove.txt
tests/test_trectools.py

In #1184, I tweaked the spacing of `trec_eval` metrics, but the spacing looks worse now. Reverts back to original format, but makes judged@k metric outputs to look the same.

Change trec_eval output spacing back to previous alignment

---

pyserini/prebuilt_index_info.py

a fix to the pr  #1201. passed the `python -m unittest integrations/dense/test_mrtydi.py`

update md5 of ms marco prebuilt index

---

docs/working-with-entity-linking.md
scripts/entity_linking.py

Refactored the EL script to support the updated REL code.
I followed the author's suggestions for [creating a new Mention Detection pipeline](https://github.com/informagi/REL/blob/main/tutorials/02_E2E_Entity_Linking.md#replacing-the-mention-detection-module).
It assumes that REL is installed via pip from their repo [as instructed](https://github.com/informagi/REL#option-2-installation-from-source-code).
Tested on a small portion of docs00.json (first 100 lines) that is generated while pre-processing the msmarco-passage for indexation with pyserini.
This approach, as the original code, is very RAM intensive. Batching and multi-processing can be added to improve the pipeline's performance.

Updated script to run with the SpacyNER tagger and REL linker

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

The reproduction was done on Ubuntu 18.04, 32gb RAM and 1Tb HDD. The process went smoothly, only notable difference was in the indexing time which took a little longer than README suggested. I suspect this is because of my HDD drive.

Reporoduction Log Update

---

pyserini/eval/trec_eval.py

Cast the doc_id column as a string to fix the bug below
```
File "/home/ogundepo/anaconda3/envs/pyserini/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/ogundepo/anaconda3/envs/pyserini/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/ogundepo/anaconda3/envs/pyserini/lib/python3.8/site-packages/pyserini/eval/trec_eval.py", line 83, in <module>
judged = len(pd.merge(run_cutoff[[0,2]], qrels[[0,2]], on = [0,2])) / len(run_cutoff)
File "/home/ogundepo/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 107, in merge
op = _MergeOperation(
File "/home/ogundepo/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 704, in …
```

Quick bug fix with trev_eval

---

pyserini/search/lucene/_searcher.py
tests/test_search.py
tests/test_search_lucene8.py

Ref https://github.com/castorini/anserini/pull/1979
Exposes hooks from Anserini.
Sample code:
```python
from pyserini.search.lucene import LuceneSearcher
searcher = LuceneSearcher.from_prebuilt_index('robust04')
searcher.set_rm3(debug=True)
hits = searcher.search('hubble space telescope')
for i in range(0, 10):
print(f'{i+1:2} {hits[i].docid:7} {hits[i].score:.5f}')
feedback_terms = searcher.get_feedback_terms('hubble space telescope')
searcher = LuceneSearcher.from_prebuilt_index('robust04')
searcher.set_rocchio(debug=True)
hits = searcher.search('hubble space telescope')
for i in range(0, 10):
print(f'{i+1:2} {hits[i].docid:7} {hits[i].score:.5f}')
feedback_terms = searcher.get_feedback_terms('hubble space telescope')
```
cc/  @ola13

Add ability to extract feedback terms

---

integrations/dense/test_encode.py

Getting this test failure on `tuna`:
```
======================================================================
FAIL: test_unicoil_encode_as_jsonl (integrations.dense.test_encode.TestSearchIntegration)
----------------------------------------------------------------------
File "/tuna1/scratch/jimmylin/pyserini/integrations/dense/test_encode.py", line 130, in test_unicoil_encode_as_jsonl
self.assertAlmostEqual(hit.score, 18.401899337768555, places=4)
AssertionError: 18.402000427246094 != 18.401899337768555 within 4 places (0.0001010894775390625 difference)
----------------------------------------------------------------------
```
Reducing the tolerance of score matching.

Fix flaky test by increasing score tolerance

---

integrations/papers/test_sigir2021.py

The pre-built Robust04 index changed, so the test cases need to change accordingly also.

Fix integrations/papers/test_sigir2021.py

---

docs/2cr/miracl.html
pyserini/resources/miracl.yaml
scripts/repro_matrix/defs_miracl.py
scripts/repro_matrix/generate_html_miracl.py
scripts/repro_matrix/miracl_html_table_row.template
scripts/repro_matrix/run_all_miracl.py

1. fix scores: ndcg -> ndcg@10
2. fix scores for `id` and `th`, whose qrels was a bit off (hgf is up-to-date now)
3. fix css format of `miracl.html` as previous slack discussion
Currently the webpage looks like this:

MIRACL BM25 scores fix

---

docs/prebuilt-indexes.md
pyserini/prebuilt_index_info.py
pyserini/resources/index-metadata/lucene-index.hc4-v1.0.20221025.c4a8d0.README.md
pyserini/resources/index-metadata/lucene-index.neuclir22-en.20221025.c4a8d0.README.md
pyserini/resources/index-metadata/lucene-index.neuclir22.20221025.c4a8d0.README.md

Updated docs for MIRACL pre-built indexes.

Add pre-built HC4 and NeuCLIR 2022 indexes

---

scripts/repro_matrix/run_all_miracl.py

Fixes a small difference on my Mac Studio (M1 chip):
```
condition mdpr-tied-pft-msmarco.hi:
- split: train
nDCG@10: 0.3684 [FAIL] expected 0.3685
R@100  : 0.7780 [OK]
- split: dev
nDCG@10: 0.3830 [OK]
R@100  : 0.7755 [OK]
```

Increase tolerance on a flaky MIRACL test

---

README.md
docs/prebuilt-indexes.md
pyserini/prebuilt_index_info.py
pyserini/resources/index-metadata/lucene-index.beir-v1.0.0-flat.20221116.505594.README.md
pyserini/resources/index-metadata/lucene-index.beir-v1.0.0-multifield.20221116.505594.README.md
pyserini/resources/index-metadata/lucene-index.beir-v1.0.0-splade_distil_cocodenser_medium.20221116.505594.README.md
scripts/beir/gather_beir_index_stats.py
scripts/repro_matrix/run_all_beir.py

Tested, this passes:
```
python scripts/repro_matrix/run_all_beir.py
```

Install new Lucene 9 pre-built indexes for BEIR

---

README.md
docs/2cr/odqa.html
pyserini/resources/naturalquestion.yaml
pyserini/resources/triviaqa.yaml
scripts/repro_matrix/defs_odqa.py
scripts/repro_matrix/generate_html_odqa.py
scripts/repro_matrix/odqa_html_table_row_gar-rrf.template
scripts/repro_matrix/odqa_html_table_row_rrf.template
scripts/repro_matrix/run_all_odqa.py
scripts/repro_matrix/utils.py

Update:
- Regression test script for all methods
- tested on ORCA, both TriviaQA and NaturalQuestion passed regression tests
- 2cr webpage updated
- ground truth changed for DPR-Hybrid (improved performance on NQ using single-nq setting + nq-test instead of multi + dpr-nq-test)
- `--topics` choices changed from 'naturalquestion' and 'triviaqa' to 'nq' and 'tqa'

Update odqa 2cr for all remaining methods

---

docs/experiments-ance.md
docs/experiments-bpr.md
docs/experiments-distilbert_kd.md
docs/experiments-distilbert_tasb.md
docs/experiments-dkrr.md
docs/experiments-dpr.md
docs/experiments-sbert.md
docs/experiments-tct_colbert-v2.md
docs/experiments-tct_colbert.md

During the holidays, I reran a bunch of dense retrieval experiments on `orca`. I noted minor score changes... nothing major.

Update dense retrieval reproduction logs; minor updates to scores

---

docs/2cr/msmarco-v1-passage.html
pyserini/resources/msmarco-v1-passage.yaml

Generate docs automatically:
```
python scripts/repro_matrix/generate_html_msmarco.py \
--collection v1-passage > docs/2cr/msmarco-v1-passage.html
```

Integrate new pre-encoded queries for MS MARCO v1 passage conditions into 2CR framework

---

requirements.txt

https://github.com/castorini/pyserini/pull/1419 - latest pre-encoded queries was encoded with pandas 1.5.1 by Xueguang.
Causes backward compatibility issues; works for pandas 1.4.4 (so 1.4.x should work), but fails on 1.3.5.
Solution is to bump up requirements.

Update requirements.txt - pandas

---

pyserini/search/faiss/__main__.py

Currently `faiss` search doesn't have `--remove-query` option in command line as `lucane` does.
Added `--remove-query` option to remove the query from the results.

add remove-query option to command line

---

pyserini/index/lucene/_indexer.py
tests/test_index_otf.py

This allows us to pass additional arguments as discussed here [#2061](https://github.com/castorini/anserini/pull/2061).
Arguments marked as required by `IndexCollection.Args` but not required by the `SimpleIndexer` (e.g. `collection`) are handled appropriately so no need to pass these parameters when using the class with Args.

Update Lucene Indexer to match SimpleIndexer in Anserini

---

pyserini/index/lucene/_indexer.py
tests/test_index_otf.py

Python bindings for https://github.com/castorini/anserini/pull/2062
Requested feature: https://github.com/castorini/pyserini/issues/1443
This now works:
```python
>>> from pyserini.index.lucene import LuceneIndexer, IndexReader
>>> indexer = LuceneIndexer('index')
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2023-02-23 15:32:17,020 INFO  [main] index.SimpleIndexer (SimpleIndexer.java:115) - Using DefaultEnglishAnalyzer
2023-02-23 15:32:17,022 INFO  [main] index.SimpleIndexer (SimpleIndexer.java:116) - Stemmer: porter
2023-02-23 15:32:17,022 INFO  [main] index.SimpleIndexer (SimpleIndexer.java:117) - Keep stopwords? false
2023-02-23 15:32:17,023 INFO  [main] index.SimpleIndexer (SimpleIndexer.java:118) - Stopwords file: null
>>> …
```

Add ability to append to existing index

---

pyserini/index/lucene/__init__.py
pyserini/index/lucene/_indexer.py
scripts/msmarco-passage/index_msmarco_passage2.py
tests/test_index_otf.py

Pyserini counterpart to https://github.com/castorini/anserini/pull/2065
Clarifies three six different methods to add documents to index:
+ add string JSON, Python dict, and Jackson JSON node
+ add single doc/add batch

Improve (multi-threaded) batch indexing capabilities to LuceneIndexer

---

pyserini/prebuilt_index_info.py
pyserini/resources/beir.yaml
scripts/beir/gather_beir_index_stats.py
scripts/repro_matrix/run_all_beir.py

e.g., `beir-v1.0.0-trec-covid-flat` -> `beir-v1.0.0-trec-covid.flat `
dash to dot

Rename BEIR BM25 prebuilt indexes

---

pyserini/prebuilt_index_info.py
scripts/repro_matrix/run_all_beir.py

I mistakenly put beir's FAISS index under Lucene index in `prebuilt_index_info` in [this PR](https://github.com/castorini/pyserini/pull/1446)
- modified `pre_built_index.py` to put beir's FAISS index under FAISS_INDEX_INFO
- add `contriever` to the models in `run_all_beir`

Fix beir faiss index

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

Device: MacBook Air (M2 chip)
Maven version: Apache Maven 3.9.0
Java version: 11.0.18
Default locale: en_KR
Platform encoding: UTF-8
OS name: "mac os x", version: "13.2.1", arch: "aarch64", family: "mac"
No issues encountered.

Add to Pyserini MS MARCO reproduction logs

---

docs/experiments-aggretriever.md
pyserini/encode/_aggretriever.py
pyserini/encoded_query_info.py
pyserini/prebuilt_index_info.py
tests/test_encoder.py

In this PR, we add 1. prebuilt index, query embedding and huggingface model path into readme 2. add test_aggretriever_distilbert_encoder_cmd() and test_aggretriever_cocondenser_encoder_cmd() to tests.test_encoder

fix aggretriever readme with prebuilt index and add encoder test

---

pyserini/prebuilt_index_info.py
pyserini/search/lucene/irst/_searcher.py
tests/test_prebuilt_index.py

After discuss with @MXueguang , we agree that this is a better org than #1490
Lucene8 deprecated indexes have been removed.
The diff is really ugly, but the high-level organization is as follows -

Reorganize info for pre-built indexes into Python dictionaries

---

scripts/repro_matrix/run_all_mrtydi.py

Minor errors with `mrtydi`:
```
condition mdpr-tied-pft-msmarco.th:
- split: train
MRR@100: 0.2334 [OK]
R@100  : 0.5848 [FAIL] expected 0.5851
- split: dev
MRR@100: 0.2407 [OK]
R@100  : 0.5795 [OK]
- split: test
MRR@100: 0.2693 [OK]
R@100  : 0.5945 [OK]
```

Fix flaky mrtydi test on M1

---

pyserini/prebuilt_index_info.py
tests/test_prebuilt_index.py

Top-level organization looks like this:

Reorganize FAISS pre-built index info

---

docs/experiments-tct_colbert-v2.md
docs/experiments-tct_colbert.md

hey @jacklin64 @justram I reproduced the TCT-ColBERTv1/v2 runs with the new renamed indexes. Everything looks good.

Reproduce TCT-ColBERTv1/v2 runs

---

pyserini/2cr/msmarco-v1-doc.yaml
pyserini/2cr/msmarco-v1-passage.yaml
pyserini/2cr/msmarco-v2-doc.yaml
pyserini/2cr/msmarco-v2-passage.yaml
pyserini/search/lucene/_searcher.py

Can perform relevance feedback without needing docvectors in the index
Pyserini counterpart of exposing this Anserini feature: https://github.com/castorini/anserini/pull/2108

Take advantage of OTF docvector parsing for performing relevance feedback

---

docs/experiments-msmarco-passage.md

Macbook Pro M1 pro, 14 inch
OS name: "mac os x", version: "13.2.1", arch: "aarch64", family: "mac"
Java version: 17.0.7, vendor: Azul Systems, Inc.
Maven: apache-maven-3.9.2
Python: Python 3.10.9

Reproduce success for Pyserini: BM25

---

pyserini/search/lucene/__main__.py

hey @alexlimh as part of #1445 - you accidentally removed the branch when we specify pre-encoded queries, i.e., `args.encoder` isn't set. Adding back in.

Fix bug with ImpactSearcher initialization

---

pyserini/2cr/miracl.py
pyserini/2cr/mrtydi.py
setup.py

Main changes are these:
```
with open('pyserini/2cr/mrtydi.yaml') as f:
```
to
```
with open(pkg_resources.resource_filename(__name__, 'mrtydi.yaml')) as f:
```
so that the PyPI package can read the config files correctly.
Other minor tweaks to touch up to conform to PEP8.
cc/ @jasper-xian

Refactor 2CR MIRACL/MrTyDi PyPI packaging

---

docs/experiments-atomic-bm25.md
pyserini/prebuilt_index_info.py
pyserini/query_iterator.py
pyserini/resources/index-metadata/lucene-index.atomic.20230525.a7df7f.README.md

Add prebuilt indexes for reproducing atomic bm25 baselines and a README showing how to reproduce the results.
(they are currently hosted on my personal huggingface space)
Also a small change in the query iterator to work with `jsonl` files
Note:
- need to update links to the indexes once they are moved to the `rgw.cs.uwaterloo.ca` server
- also a related PR adding the topics and qrels files https://github.com/castorini/anserini-tools/pull/51
I did a quick test of the commands given in `docs/experiments-atomic-bm25.md` using the `small` settings and verified that the numbers match up with those given in https://docs.google.com/spreadsheets/d/1wSi_79Qx3GA1WAirwvoapiWJ4m2bPRM_rtUWRZ2qRIo/edit#gid=0

Add AToMiC bm25 reproduction baselines

---

docs/2cr/msmarco-v1-passage.html
pyserini/2cr/msmarco-v1-passage.yaml
pyserini/2cr/msmarco.py
pyserini/2cr/msmarco_html_v1_passage.template
pyserini/encoded_query_info.py
pyserini/prebuilt_index_info.py

**Reproduction Instructions**
--
**TREC 2019**
Search:
``` bash
python -m pyserini.search.faiss \
--threads 16 --batch-size 128 \
--index msmarco-v1-passage.openai-ada2 \
--topics dl19-passage --encoded-queries openai-ada2-dl19-passage \
--output run.msmarco-v1-passage.openai-ada2.dl19.txt
```
Eval:
```bash
python -m pyserini.eval.trec_eval -c -l 2 -m map dl19-passage run.msmarco-v1-passage.openai-ada2.dl19.txt
python -m pyserini.eval.trec_eval -c -m ndcg_cut.10 dl19-passage run.msmarco-v1-passage.openai-ada2.dl19.txt
python -m pyserini.eval.trec_eval -c -l 2 -m recall.1000 dl19-passage run.msmarco-v1-passage.openai-ada2.dl19.txt
```
---
**TREC 2020**
Search:
```bash
python -m pyserini.search.faiss \
--threads 16 --batch-size 128 \
--index msmarco-v1-passage.openai-ada2 \
--topics dl20 …
```

Add OpenAI ada2 2CR (reg/hyde)

---

pyserini/util.py

After pandas 2.0.0, using -1 for display.max_colwidth was removed in favor of None. Using -1 throws a ValueError. 
Reference from pandas: https://github.com/pandas-dev/pandas/pull/49295/files
See additional discussion here: https://github.com/castorini/pyserini/issues/1563

Add support for pandas v2.0.0+.

---

docs/experiments-msmarco-doc.md
docs/experiments-msmarco-passage.md

Environment Details: 
+ MacBook Pro Apple M2, 16GB RAM, Ventura 13.3 
+ Apache Maven 3.9.2
+ Java version: 20.0.1
+ Python 3.10.9
Issues:
+ pip install pyserini gave me a problem. nmslib wasn't installed. Similar to this issue  [#1551](https://github.com/castorini/pyserini/issues/1551).
+ I used the command below to resolve the error: 
`CFLAGS="-mavx -DWARN(a)=(a)" pip install nmslib`
and then just installed the remaining using `pip install pyserini` again.

Reproducing experiment results for MS-MARCO passage and document ranking

---

docs/experiments-nfcorpus.md

This cl adds `sahel-sh` to the Repro log in experiments-nfcorpus.md

repro log for experiments-nfcorpus.md

---

docs/conceptual-framework.md
docs/experiments-nfcorpus.md

Adding reproduction logs for:
- conceptual-framework.md
- experiments-nfcorpus.md
Environment:
- Results were reproduced on `orca`
- Apache Maven: 3.9.2 
- Java version: 11.0.13
- Python: 3.8.16
Everything works as expected, all results were reproduced.

Add repro logs for biencoder arch. and NFCorpus

---

docs/conceptual-framework2.md

Adding `sahel-sh` to `conceptual-framework2.md`'s repro log.

Update conceptual-framework2.md with repro log

---

integrations/clprf/test_clprf.py
integrations/clprf/test_trec_covid_r3.py
integrations/clprf/test_trec_covid_r4.py
scripts/classifier_prf/cross_validate.py

qrels removed from src/main/resources/topics-and-qrels/ in anserini; use tools/topics-and-qrels/ instead.

Fix clprf integration tests due to path changes in anserini

---

docs/experiments-msmarco-passage.md

**OS**: macOS Ventura Version 13.5 
**Hardware**: M2 MacBook Pro (2023), 16 GB RAM 
**Conda**: 23.7.2 
**Python**: (Conda Environment): 3.8.17
**Java**: (Conda Environment) 11.0.13
**Maven**: (Conda Environment) 3.9.4
**Result**: I was able to replicate (most of) the Indexing, Retrieval & Evaluation steps with Pyserini on my machine with the above settings. Outputs are the same as listed in the document.  
**Additional Comment**: I encountered two (and only two) failed unit tests (from running “python -m unittest”) when following the “pyserini/docs/installation.md” file. Namely,
- test_remove_undjudged (tests.test_trectools.TestTrecTools)
- test_undjudged_keep (tests.test_trectools.TestTrecTools)
This seems to be caused by the **TREC evaluation tool**. When running the following command: …

Add an entry in Pyserini's Passage Ranking Experiment Reproduction Log for ugrad onboarding

---

docs/experiments-msmarco-passage.md

Environment:
Apple m1
While following `docs/installation.md` faced trouble with pip installation of `Pyserini`. 
Following are the steps I followed before encountering the error:
1. Environment creation and it's activation:
```
$ conda create -n pyserini python=3.8
$ conda activate pyserini
```
2. JDK 11 installation:
`$ conda install -c conda-forge openjdk=11
`
3. Pip installation for Pyserini:
`pip install pyserini`
Referring this GitHub [issue](https://github.com/nmslib/nmslib/issues/476) I was able to overcome the issue with `nmslib` (previously the build was getting stuck for both `lightgbm` and `nsmlib`). However, the one with `lightgbm` still persists.
Screenshot for the error:

Adds reproduction logs for onboarding docs

---

pyserini/search/lucene/_impact_searcher.py

`min_idf` is a class attribute and not part of the search and batch_search input args.

Update _impact_searcher.py to remove min_idf from docstrings.

---

pyserini/search/lucene/_impact_searcher.py

https://github.com/castorini/anserini/commit/e475cc4e885f5fbb223533d75a2da7abaa618c6c renames `document/documentByField` functions to `doc/doc_by_field`. This cl changes the function calls in _impact_searcher.py to match the new names to fix the following error:
````
File ".../lib/python3.10/site-packages/pyserini/search/lucene/_impact_searcher.py", line 248, in doc
lucene_document = self.object.document(docid)
AttributeError: 'io.anserini.search.SimpleImpactSearcher' object has no attribute 'document'
```

Update _impact_searcher.py to use renamed java functions.

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

Environment:
OS: Student Environment (`linux.student.cs.uwaterloo.ca`) - Ubuntu2204
Java version: 11.0.13 (through conda)
Python version: 3.8.17 (through conda)
Maven version: 3.9.4
Results:
- Successfully reproduced [Pyserini: BM25 Baseline for MS MARCO Passage Ranking
](https://github.com/castorini/pyserini/blob/master/docs/experiments-msmarco-passage.md)
- Successfully reproduced [Pyserini: A Conceptual Framework for Retrieval](https://github.com/castorini/pyserini/blob/master/docs/conceptual-framework.md)
- Successfully reproduced [Pyserini: Contriever Baseline for NFCorpus](https://github.com/castorini/pyserini/blob/master/docs/experiments-nfcorpus.md)
- Had to run `ulimit -t unlimited` before running on the Student CS host to remove CPU time limit (as documented here: …

Add to reproduction logs for onboarding docs

---

docs/experiments-atomic-ViT-L-14.laion2b_s32b_b82k.md
pyserini/prebuilt_index_info.py
scripts/atomic/README.md
scripts/atomic/convert_embeddings.py
scripts/atomic/data.py
scripts/atomic/reader.py

Converts raw numpy embeddings (`embeddings.npy` and `ids.txt`) files to pyserini-format topics (`topic.json`) and encoded queries (`embedding.pkl`) to be able to use `pyserini.search.faiss` to run baselines on the AToMiC dataset

Add script to convert AToMiC raw numpy embeddings to pyserini format

---

docs/conceptual-framework2.md
docs/experiments-nfcorpus.md

Suggestions per #1637 - @sahel-sh would you mind taking a look?

Update onboarding docs per #1637

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

Adding reproduction logs:
1. BM25 Baseline for MS MARCO Passage Ranking in Pyserini
2. A Conceptual Framework for Retrieval
3. Contriever Baseline for NFCorpus
4. A Deeper Dive into Dense and Sparse Representations
My comments for the third part:
This task was a little bit time-consuming due to hardware and internet limitations, which was to be expected. Hopefully, I managed to allocate additional memory using a virtual machine, increasing it from 12 GB to 16 GB and switching to a faster internet connection. It was still slow, but it worked for me. As I am going to submit this pull request, some changes in this section have been applied. One is a customizable batch size based on system capacity; it is a good idea; however, a batch size of 32 still remains excessive for regular PCs. …

Add to onboarding reproduction logs by Melvin Mokhtari

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

Successfully reproduced results from each onboarding module in **pyserini**. Added my entry to reproduction logs in `experiments-msmarco-passage.md`, `conceptual-framework.md`, `experiments-nfcorpus.md`, and `conceptual-framework2.md`.
Macbook Air 2019
MacOS Ventra 13.3.1
Apache Maven 3.9.4
conda 4.12.0
Python 3.9.13
Python (in conda env) 3.8.18
openjdk 15.0.2

Add to onboardng reproduction logs - pyserini

---

docs/conceptual-framework2.md

Adding reproduction logs for:
- conceptual-framework2.md
Environment:
- Results were reproduced on orca
- Apache Maven: 3.9.2
- Java version: 11.0.13
- Python: 3.8.16
Results:
All results were reproduced as expected.

Add onboarding repro logs

---

pyserini/2cr/miracl.py
pyserini/2cr/miracl.yaml
pyserini/2cr/mrtydi.py
pyserini/2cr/msmarco-v1-passage.yaml
pyserini/2cr/msmarco.py
scripts/jobs.regressions-all.txt

After recent upgrade of `tuna` to Unbuntu 22, we're using the machine a "ground truth" for the regression numbers. This PR pins the results to `tuna` - thus small changes from before.

Tweak regression numbers to pin to tuna results as ground truth

---

docs/2cr/atomic.html
pyserini/2cr/atomic.py
pyserini/2cr/atomic.yaml
pyserini/2cr/atomic_html.template
pyserini/2cr/atomic_html_row.template
pyserini/encoded_query_info.py
pyserini/search/_base.py

AToMiC dense 2CR for model ViT-L-14.laion2b_s32b_b82k
Related PRs: https://github.com/castorini/anserini/pull/2219 https://github.com/castorini/anserini-tools/pull/57 https://github.com/castorini/pyserini-data/pull/6

2CR for dense AToMiC retrieval

---

docs/experiments-wiki-corpora.md
pyserini/encoded_query_info.py

The faiss indexes were renamed as of commit: https://github.com/castorini/pyserini/commit/b841b53037ab3042a5f5f2d6e14f7a316da07c11. Also, the encoded queries names were inconsistent.

Fix wiki corpora experiments doc

---

pyserini/encode/__init__.py
pyserini/encode/__main__.py
pyserini/encode/_openai.py
pyserini/encode/query.py
pyserini/search/__init__.py
pyserini/search/faiss/__init__.py
pyserini/search/faiss/__main__.py
pyserini/search/faiss/_searcher.py

DEPENDENCIES ADDED: 
```
openai             0.28.0
tiktoken           0.4.0
```
TODO: incorporate OpenAI API query encoder into `pyserini.search`
To reproduce the [nfcorpus](https://github.com/castorini/pyserini/blob/master/docs/experiments-nfcorpus.md) experiment:
Indexing: 
```bash
python -m pyserini.encode \
input   --corpus collections/nfcorpus/corpus.jsonl \
--fields title text \
output  --embeddings indexes/faiss.nfcorpus.contriever-msmacro \
--to-faiss \
encoder --encoder text-embedding-ada-002 \
--encoder-class openai-api \
--use-openai \
--rate-limit 3500 \
--device cpu \
--dimension 1536 \
--fields title text
```
Query Encoding:
```bash
python pyserini/encode/query.py \
--topics collections/nfcorpus/queries.tsv \
--encoder openai-api \
--max-length 512 \
--output …
```

Add OpenAI text-embedding-ada-002 API-based encoding

---

integrations/dense/test_tct_colbert.py

Minor tweak to fix this issue:
```
======================================================================
FAIL: test_msmarco_passage_tct_colbert_bf_d2q_hybrid_otf (test_tct_colbert.TestTctColBert)
----------------------------------------------------------------------
File "/Users/jimmylin/workspace/pyserini/integrations/dense/test_tct_colbert.py", line 108, in test_msmarco_passage_tct_colbert_bf_d2q_hybrid_otf
self.assertAlmostEqual(score, 0.3647, places=4)
AssertionError: 0.3646 != 0.3647 within 4 places (0.0001000000000000445 difference)
----------------------------------------------------------------------
Ran 33 tests in 31708.497s
```

Fix flaky test due to upgrade of dependent libs on Apple M processor

---

pyserini/encode/_openai.py
pyserini/search/faiss/_searcher.py
requirements.txt

Fixes some deprecation issues after OpenAI's 1.0.0 update

Update OpenAI embeddings API to version >= 1.0.0

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

Everything worked accordingly.
- Operating System:
- WSL 2 on Windows 11
- Development Environment:
- Python 3.10.12
- Java 11.0.20.1 2023-08-24
- Hardware:
- Processor: Intel Core i7-13650HX, 2.60 GHz
- RAM: 32 GB
- Storage: SSD Drive - NVMe Micron 2400
- GPU: NVIDIA GeForce RTX 4060
---
One more thing, there was this discrepancy with the output of this command in `experiments-msmarco-passage.md`, where the number of the lines and the characters were the same, but the number of the words were one less than the output mentioned in the file:
```
wc tools/topics-and-qrels/topics.msmarco-passage.dev-subset.txt
6980  48334 290193 tools/topics-and-qrels/topics.msmarco-passage.dev-subset.txt
```

Add reproduction logs

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

**Setup:**
Python: 3.10.13
Java: 11.0.13
Maven: 3.9.5
OS: MacOS Monterey Version 12.5
Processor: Apple M1 Pro
Memory: 16G
**Outcome:** I was able to reproduce the results, with the exception of a couple instances of floating point error.
One issue that needed to be resolved for me was a missing import of `CosDprDocumentEncoder` in `pyserini/encode/__init__.py`.

Add to onboarding reproduction logs

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

Adding to reproduction logs for all Pyserini onboarding steps.
Everything worked flawlessly, except one issue:
Unit tests were running commands using `python` whereas my Ubuntu install uses `python3`. Running `alias python=python3` in terminal fixes the problem, but a better solution is to install the [python-is-python3](https://stackoverflow.com/questions/73221704/ubuntu-linux-gmsh-gives-sh-1-python-not-found-error) package.
Ubuntu 22.04.3 LTS running inside a Docker container on Windows 11 Pro. (Used [VScode Dev containers](https://code.visualstudio.com/docs/devcontainers/containers))
Python 3.10.12
Java 11.0.21
Maven 3.6.3
RAM: 64 GB
Storage: 2 TB
Processor: Core i9-13900k

Adding to replication logs

---

pyserini/output_writer.py
pyserini/search/__init__.py
pyserini/search/lucene/__init__.py
pyserini/search/lucene/_geo_searcher.py
pyserini/search/lucene/_hnsw_searcher.py
pyserini/search/lucene/_impact_searcher.py
pyserini/search/lucene/_searcher.py
tests/test_index_otf.py
tests/test_search.py
tests/test_search_lucene8.py

Counterpart of https://github.com/castorini/anserini/pull/2310
+ Major change is the introduction of `ScoredDoc`: Searchers now use ScoredDoc instead of class-specific Result objects.
+ Introduced simple bindings to Lucene HNSW searcher.

Refactor search code to complement Anserini refactoring

---

integrations/lucenesearcher_anserini_checker.py
pyserini/search/hybrid/__main__.py
scripts/repro_matrix/run_all_odqa.py

+ from Anserini refactoring (renamed args)
+ from pooling and l2norm config for autoencoder (https://github.com/castorini/pyserini/pull/1722/)

Fixed broken tests 

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

Everything worked, except one minor issue encountered in the [last line of BM25 Baseline for MS MARCO Passage Ranking in Pyserini / Interactive Retrieval](https://github.com/castorini/pyserini/blob/master/docs/experiments-msmarco-passage.md#interactive-retrieval), the line `hits[0].raw` would error: 
```
AttributeError: 'io.anserini.search.ScoredDoc' object has no attribute 'raw'
```
The output from the builtin `dir(hits[0])` gives:
```py
['_JavaClass__cls_storage', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__javaclass__', '__javaconstructor__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__pyx_vtable__', '__reduce__', '__reduce_ex__', '__repr__', …
```

Updated reproduction logs

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

Reproduced on Apple M2
8 GB RAM
macOS Sonoma 14.2.1
Python 3.10.13
maven 3.9.6
Java 11.0.21
Cannot build wheels **lightgbm** and **nmslib** during this build step
```bash
pip install -e .
```
For **lightgbm**, install libomp with
```bash
brew install libomp 
```
Taken from: https://github.com/microsoft/LightGBM/issues/6035
For **nmslib**, the issue seems to be an issue with python 3.11 and pybind. Downgraded to python 3.10.
Taken from: https://github.com/pybind/pybind11/discussions/4333

Add to Reproduction Logs

---

docs/installation.md

In the installation guide to install Pyserini on Apple M-series, `conda install -c conda-forge nmslib -y` throws the following error (as of Jan 2024):
```
PackagesNotFoundError: The following packages are not available from current channels
```
Following [here](https://github.com/nmslib/nmslib/issues/476#issuecomment-1594889437), the command to install `nmslib` on Apple M-series is fixed in this PR.

Update installation.md to fix nmslib installation error on Apple M-series

---

docs/2cr/msmarco-v1-passage.html
docs/prebuilt-indexes.md
pyserini/2cr/msmarco-v1-passage.yaml
pyserini/2cr/msmarco.py
pyserini/encoded_query_info.py
pyserini/prebuilt_index_info.py

It looks like the 2cr HTML page needed to be updated for BGE as well, the yaml was not consistent with the HTML page - from this commit https://github.com/castorini/pyserini/pull/1781

Add cohere-embed-english-v3.0 to msmarco-v1-passage 2cr

---

pyserini/eval/trec_eval.py
pyserini/tokenize_json_collection.py
requirements.txt
tests/test_index_reader.py
tests/test_prebuilt_index.py
tests/test_tokenization.py

Fixed failure in test_bm25_vectorizer_train where values were slightly off, perhaps due to an underlying update
Added Pyarrow requirement to avoid the error:
```
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
```
Some other small changes as well to deal with warnings

Fix unittest warnings and failure

---

pyserini/trectools/_base.py

To clear the warning:
```
FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1.0, 0.0]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
self.run_data.loc[self.run_data['topic'] == topic, 'score'] = scores
```

Fix unittest warning

---

pyserini/encode/_base.py
pyserini/encode/_clip.py
pyserini/index/faiss.py
pyserini/query_iterator.py
tests/test_hybrid_search.py
tests/test_multimodal_search.py

- Support multimodal retrieval settings: T2I, I2T, I2I, T2T
- Support jsonl format for indexing and query
- Add MultimodalQueryIterator
- Add test case
- Clean some redundant codes
See [test case](https://github.com/justram/pyserini/blob/5d25c8905119e7e83a07c7a138cb2ae5dea474ce/tests/test_multimodal_search.py#L73-L99)
```shell
echo "Encoding..."
python -m pyserini.encode \
input   --corpus $CORPUS \
--fields text \
output  --embeddings $EMB_PATH \
--to-faiss \
encoder --encoder $CKPT \
--fields text \
--dimension $EMB_DIM \
--l2-norm \
--batch 128 \
--max-length 77 \
--device cpu
echo "Indexing..."
python -m pyserini.index.faiss \
--input $EMB_PATH --output $INDEX_PATH --dim $EMB_DIM
echo "Searching..."
python -m pyserini.search.faiss \
--index $INDEX_PATH \
--topics $TOPICS …
```

support multimodal retrieval and cleanup redundant codes

---

docs/2cr/msmarco-v2-doc.html
docs/2cr/msmarco-v2-passage.html
pyserini/2cr/msmarco-v2-doc.yaml
pyserini/2cr/msmarco-v2-passage.yaml
pyserini/search/_base.py
tests/test_load_queries.py

This cl adds `dl23-unicoil*` entries to pyserini and populates the missing 2crs
TESTED=the existing unittest updated,  manully viewed the generated report

Added missing 2crs for dl23 passage and doc

---

docs/usage-index.md

- At line 259 : no such file (usage-encode.md) exists.
- At line 266, 275, 283,293 : 
Below is the screenshot of [pyserini/index/faiss.py](https://github.com/castorini/pyserini/blob/master/pyserini/index/faiss.py) file
It expects a Folder containing the file, not the file path.
- At line 294 : Extra 'slash' which gives error in python terminal.
- At line 245 : The model repository name changed the actual one available on [huggingface](https://huggingface.co/castorini/unicoil-msmarco-passage) 
This change resolves issue number #1767
I have other suggestions as well. Starting from this small contribution. More can be expected soon as I'm actively using this. Thank you

Refactored/ Corrected a part of  Documentation 

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

System setup:
OS: macOS Ventura 13.4
Memory: 16GB
Chip: Apple M1 Pro
Python Version: 3.10.13
Java Version: 21.0.3
Maven: 3.9.2
Everything worked perfectly!
Suggestion: When I went through Pyserini: BGE-base Baseline for NFCorpus / Data Prep, I was curious why we added Q0 instead of 0 as the artifact in Anserini. It seems to be used in trec_eval.py, and I think explaining it would be helpful for others to understand the reason of the change. (I have added the change in the PR, we could reword or ignore that change if it is not useful.)

Onboarding tasks billycz8

---

pyserini/2cr/beir.py

+ separate cqa
+ report to three decimal places
Run this:
```
python -m pyserini.2cr.beir --all --display-commands --dry-run
```
And you'll get this:
```
BM25-flat          BM25-mf             SPLADE           Contriever     Contriever-msmarco  BGE-base-en-v1.5   cohere (en-v3.0)
nDCG@10   R@100    nDCG@10   R@100    nDCG@10   R@100    nDCG@10   R@100    nDCG@10   R@100    nDCG@10   R@100    nDCG@10   R@100    
--------------     --------------     --------------     --------------     --------------     --------------     --------------
trec-covid                  0.595   0.109      0.656   0.114      0.727   0.128      0.273   0.037      0.596   0.091      0.781   0.141      0.818   0.159
bioasq                      0.522   0.769      0.465   0.715      0.498   0.739      0.302   0.541 …
```

Improve reporting of BEIR results

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

Setup:
I did this on Google Collab with the following specifications:
OpenJDK 21.0.2
Python 3.10.12
On Google Colab, the intial version was JDK 11 and so I had to upgrade that after which the everything ran smoothly. One problem with doing this on Google Colab was that sometimes the session had to be restarted at which point I lost all the work I had done. To fix this, I had to create a back up on my Google Drive.

Added to Reproduction Logs

---

docs/prebuilt-indexes.md
pyserini/prebuilt_index_info.py
pyserini/resources/index-metadata/lucene-inverted.msmarco-v2.1-doc-segmented.20240418.4f9675.README.md
pyserini/resources/index-metadata/lucene-inverted.msmarco-v2.1-doc.20240418.4f9675.README.md
pyserini/search/_base.py
scripts/generate_docs_from_prebuilt_indexes.py
tests/test_load_qrels.py
tests/test_load_queries.py

This works:
```bash
export OUTPUT_DIR="runs"
TOPICS=(msmarco-v2-doc.dev msmarco-v2-doc.dev2 dl21-doc dl22-doc dl23-doc rag24.raggy-dev); for t in "${TOPICS[@]}"
do
python -m pyserini.search.lucene --threads 16 --batch-size 128 --index msmarco-v2.1-doc --topics $t --output $OUTPUT_DIR/run.msmarco-v2.1.doc.${t}.txt --bm25
done
TOPICS=(msmarco-v2-doc.dev msmarco-v2-doc.dev2 dl21-doc dl22-doc dl23-doc rag24.raggy-dev); for t in "${TOPICS[@]}"
do
python -m pyserini.search.lucene --threads 16 --batch-size 128 --index msmarco-v2.1-doc-segmented --topics $t --output $OUTPUT_DIR/run.msmarco-v2.1.doc-segmented.${t}.txt --bm25 --hits 10000 --max-passage-hits 1000 --max-passage
done
```

Add bindings for MS MARCO V2.1 doc: prebuilt indexes, topics, qrels

---

docs/prebuilt-indexes.md
pyserini/prebuilt_index_info.py
pyserini/resources/index-metadata/index-robust04-20191213-readme.txt
pyserini/resources/index-metadata/lucene-inverted.aquaint.20240803.36f7e3.README.md
pyserini/resources/index-metadata/lucene-inverted.disk45.20240803.36f7e3.README.md
pyserini/resources/index-metadata/lucene-inverted.nyt.20240803.36f7e3.README.md
pyserini/resources/index-metadata/lucene-inverted.wapo.v2.20240803.36f7e3.README.md

disk45 (robust04), aquaint (robust05), nyt (core17), wapo.v2 (core18)
These commands work:
```
python -m pyserini.search.lucene --index robust04 --topics robust04 --output runs/run.robust04 --bm25
python -m pyserini.eval.trec_eval -c -m map -m P.30 robust04 runs/run.robust04
map                   	all	0.2531
P_30                  	all	0.3102
python -m pyserini.search.lucene --index robust05 --topics robust05 --output runs/run.robust05 --bm25
python -m pyserini.eval.trec_eval -c -m map -m P.30 robust05 runs/run.robust05
map                   	all	0.2032
P_30                  	all	0.3693
python -m pyserini.search.lucene --index core17 --topics core17 --output runs/run.core17 --bm25
python -m pyserini.eval.trec_eval -c -m map -m P.30 core17 runs/run.core17
map                   	all	0.2087 …
```

Add prebuilt indexes for newswire collections

---

integrations/papers/test_sigir2021.py

These test cases were hard-coded using a prebuilt index (robust04).
I recently rebuilt this index, and so some of the internal info has changed.
Adjusting reference values.

Fix integration tests

---

docs/experiments-ance.md
docs/experiments-bpr.md
docs/experiments-distilbert_kd.md
docs/experiments-distilbert_tasb.md
docs/experiments-dkrr.md
docs/experiments-sbert.md
pyserini/search/faiss/_searcher.py

+ Fixed the following: ance, sbert, bpr, distillbert-tasb, distillbert-kd, dkrr
+ At numpy 1.26.4, fixed following issue:
```
File "/home/jimmylin/.conda/envs/pyserini-dev7/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/jimmylin/.conda/envs/pyserini-dev7/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/tuna1/scratch/jimmylin/pyserini/pyserini/search/faiss/__main__.py", line 296, in <module>
results = searcher.batch_search(batch_topics, batch_topic_ids, args.hits, threads=args.threads,
File "/tuna1/scratch/jimmylin/pyserini/pyserini/search/faiss/_searcher.py", line 723, in batch_search
D, I = self.binary_dense_search(k, binary_k, rerank, dense_q_embs, …
```

Refactoring documentation for some dense models

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

Worked fine on MacOS (Sequoia 15.1.1) + Maven 3.9.9. I finished the onboarding, would appreciate it if I could get the Slack invite. Thanks!

Add to onboarding repro logs

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

Hi~ My onbroading journey finish!
My window computer
Operating System: Windows 10 Home Chinese Version
Java Version: 21.0.4 2024-07-16 LTS
Apache Maven Version: 3.9.9
Python Version : 3.8.10
Outcome: : Encountered issues with trec_eval and unit tests
Issues Encountered:
1. some errors occurred during the Development Installation when ensuring everything works by running the unit tests using python -m unittest. There are about 66 errors 2 failure (total 345 tests).
2. all trec_eval fail. error shows below:
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported os/arch: trec_eval/trec_eval-win-amd64
at trec_eval.getTrecEvalBinary(trec_eval.java:93)
at trec_eval.<init>(trec_eval.java:141)
at trec_eval.main(trec_eval.java:283)
i think both of the issues happen because …

Onboarding: Successful Pyserini Reproduction 

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

System: Apple Macbook Pro 2020
OS: MacOS Sonoma 14.7.2
Python: 3.10.13
Maven: 3.9.9
Java: openjdk 21.0.5
---
A Minor Problem in [FAISS Retrieval](https://github.com/castorini/pyserini/blob/master/docs/experiments-nfcorpus.md#retrieval):
When retrieving via FAISS, the process frequently froze partway through at various progress points initially at 4% with the default given `--batch 128 --threads 8`, then as I adjusted thread and batch combinations multiple times, it froze again at different points (e.g., 2%, 4%, 32%, or 86%). 
Due to these challenges, I was only able to evaluate 2,800 out of 3,237 queries for that step.
Error Message that came up during this run:
```bash
$ python -m pyserini.search.faiss \
>   --encoder-class auto --encoder BAAI/bge-base-en-v1.5 --l2-norm \
>   --pooling …
```

Onboarding add to reproduction logs

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

- Device: Apple MacBook Pro (M1 Pro)
- OS: macOS Sequoia 15.0
- Python Version: 3.11.5
- Maven Version: 3.9.9
- Java Version: OpenJDK 21.0.5
- All required steps were completed successfully.
```bash
python -m pyserini.search.faiss \
--encoder facebook/contriever-msmarco \
--index indexes/faiss.nfcorpus.contriever-msmacro \
--topics collections/nfcorpus/queries.tsv \
--output runs/run.beir-contriever-msmarco.nfcorpus.txt \
--batch 128 --threads 8 \
--hits 1000
```
While running the above command, I encountered the following error:
```
[thread 42499 also had an error]
[thread 42243 also had an error]
#
#
```
The issue was resolved by setting the `OMP_NUM_THREADS` environment variable. Setting `--threads=1` also worked, but by setting the `OMP_NUM_THREADS` variable, the command was …

Append to onboarding reproduction logs

---

pyserini/query_iterator.py

CACM topics end in `.txt`, so we want to move that branch of the if statement up to select the right topic reader.

Fix bug with selecting correct topic reader for CACM topics

---

tests-optional/test_index_faiss.py

The parameters for this test case didn't really make sense, but we ran it anyway. Upgrading to Faiss 1.9.0, it now croaks about these non-sensical parameters... so removing.

Remove non-sensical test for Faiss

---

docs/conceptual-framework3.md

Reproduced successfully with tweaks from #2099 . Added instructions for creating directories for encoded documents as mentioned in its first comment. 
Removed the section munging the corpus and made appropriate changes to the code for encoding documents so it works with the original corpus directly. I think it's easier this way because there's one less thing for beginners to worry about.

Add to onboarding reproduction logs for conceptual-framework3.md

---

pyserini/query_iterator.py
tests/test_topics_order.py

This PR aims to document what I did to address the situation described in [discussion #2119](https://github.com/castorini/pyserini/discussions/2119#discussion-8345321) where the code wasn't handling certain edge cases. This caused the process to break instead of continuing execution.
```python
def safe_sort(lst):
try:
return sorted(lst)
except:
return sorted(lst, key=str)
assert safe_sort([3, 2, 1]) == [1, 2, 3]
assert safe_sort(["A", "C", "B"]) == ["A", "B", "C"]
assert safe_sort([1, 2, "A", "B", 3, "C"]) == [1, 2, 3, "A", "B", "C"]
```

Sort as string if not all the same type

---

docs/usage-mcp.md
pyserini/server/mcp/__main__.py

Successfully reproduced `usage-mcp.md` with a few tweaks.
I'm on Windows and my Pyserini is on `orca`, which is Linux, so I couldn't run Claude Desktop.
I used Cursor with remote MCP and it worked fine. Added a note about it in the doc but not a full guide since it's not ideal and there's probably better options.
[Video demonstration](https://github.com/user-attachments/assets/82271c8a-69ad-45d3-be2e-c27f86661585)

Reproduce MCP

---

pyserini/prebuilt_index_info.py

The metadata removed from Pyserini in #2159 has been added to Anserini as of castorini/anserini#2853 as part of .castorini/anserini#2852. This PR makes it so the additional metadata actually gets loaded into Pyserini from Anserini.

Add metadata loading from Anserini

---

pyserini/prebuilt_index_info.py
pyserini/server/mcp/tools.py
pyserini/server/models.py
pyserini/server/rest/routes/indexes.py
pyserini/server/search_controller.py
pyserini/util.py

All prebuilt indexes should now be able to be searched. Sharded search got integrated into search by checking if index name contains 'shard' and 'msmarco'. For indexes that aren't tf, try to get raw document contents from 'base' index mapped in prebuilt index info. If there is no 'base' index mapped, just return docids and scores. 
Side note: it'd be convenient if prebuilt indexes had mappings for the appropriate encoder like Anserini IndexInfo.

Add support to search all indexes for MCPyserini

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

This PR adds my repro log for Pyserini.
System: WSL2
Resources: 11.3 GB RAM
Python Version: 3.11.13
Reproduced successfully.

Add repro log for Pyserini repo

---

tests/test_mcp.py

I found that when running `python -m unittest tests.test_mcp`, everything worked fine, but when running `python -m unittest discover tests`, the MCP tests failed. This is because running it directly somehow 'swallowed up' the logging, but running it with discovery had the prebuilt index print statement in stdout, which messed up the output. This filters out that log.

Fix failing MCP tests

---

docs/usage-mcp.md

Ran into a small issue, where retrieving the full text of a document returned none object even though the initial search was successful.
1. Initially, prompted Claude with `Search for "what is a lobster roll" in the msmarco-v1-passage index, returning 5 results.` as suggested in docs and Claude correctly replied. 
2. Then, I prompted Claude with `Retrieve the full text of document "7157715" from the msmarco-v1-passage index.`
3. Claude replied with: 
```
I'm encountering an error when trying to retrieve the full document text from the MS MARCO passage indexes. The error suggests that the document retrieval function is returning a None object instead of the expected document content.
This could indicate:
The document retrieval functionality may not be fully configured for the MS MARCO …
```

Add to repro

---

pyserini/server/search_controller.py

The MS MARCO v2.1 segment corpus is using `segment` as the main text field.
I find the REST search API is trying to always return the main text on `doc` field, instead of returning whatever the index has on that record. Is the REST search API trying to serve other statically typed downstream tools, instead of being a generic search API?

Update search_controller.py to support MS MARCO v2.1 segment field

---

pyserini/encode/_base.py
tests/resources/simple_mixed_modality_corpus.json
tests/test_encoder_iterator.py

Mixed modality datasets will have null fields that need to be addressed gracefully.

Fix for potential null fields in mixed modality datasets

---

pyserini/util.py
scripts/verify_url_prebuilt_indexes.py
tests/test_utils.py

- Verified that [@vincent-4’s change in PR #2091](https://github.com/castorini/pyserini/pull/2091/files) works as expected. 
- Reviewed all existing test cases that use `download_url` and `download_and_unpack_index`.  
- They either already validate via md5 checksum or do not perform checks at all.  
- Left these tests untouched because if a md5 passes then the file size must pass.
-  Added 4 unit tests for the functions and they are all passing.  
- Modified the util.py to support file size checking.
- Added a new utility unit test file.  
- Introduced three test cases on `cacm`:  
1. **download_url sanity check** – valid download with correct checksum and file size.  
2. **Checksum mismatch** – negative case, ensures failure when MD5 does not match.  
3. **File size mismatch** – …

Added file size checking for download_url and utility unit tests

---

docs/experiments-nfcorpus-vis.md

Reproduced the visualization result.
Python 3.10 did not work, then I updated to Python 3.12, then worked.

Added atlas visualization repro log

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

**Environment**
- OS: Ubuntu 22.04.5 LTS
- Python: 3.11.11 (conda)
- Java: OpenJDK 21.0.6 (conda-forge)
- Maven: 3.9.11 (conda-forge)
**Results**
Everything worked. However, when running the unit tests for Pyserini, some tests failed, and I had to manually install additional libraries (openai, faiss, uniir_for_pyserini, and clip).
**Suggestions**
When I tried to commit the reproduction logs, some extra files generated by the unit tests were also staged. It might help to add them to .gitignore (e.g., lucene-index\*, index-\*, run.\*).

add Reproduction Log entry for Pyserini onboarding

---

docs/conceptual-framework.md
docs/conceptual-framework2.md
docs/experiments-msmarco-passage.md
docs/experiments-nfcorpus.md

Operating System: macOs Sequoia 15.3.1
Working Environment: Visual Studio Code Version: 1.104.0
Successfully reproduced all the results on the Pyserini files part of the onboarding process (specifically docs/experiments-msmarco-passage.md, docs/conceptual-framework.md, experiments-nfcorpus.md, and docs/conceptual-framework2.md).
Had some initial issues with the development installation of Pyserini, and system compatibility issues that I had to troubleshoot my way through. Certain issues also popped up while running Dense retrieval runs.
Modified the no. of threads and batch size in certain retrieval runs and while creating certain indexes, in order to be able to successfully execute the runs on my laptop.
Removed the potential sentence fix on the page docs/conceptual-framework.md due to …

Add repro log 2278 w/o rewrite
